#!/usr/bin/env python3
"""Produce TikZ geometry from the independently verified finite tiling data."""
import json
from pathlib import Path
from math import sqrt
here=Path(__file__).resolve().parent
board=json.loads((here/'../../../../plans/week-01-lozenge-research.json').resolve().read_text())
def xy(p):return (p[0]+p[1]/2,p[1]*sqrt(3)/2)
def point(p):return '({:.9f},{:.9f})'.format(*xy(p))
def path(vs):return '--'.join(map(point,vs))+'--cycle'
lines=['% Generated by generate-geometry.py; coordinate unit = one small block edge.']
lines.append(r'\newcommand{\BoardGrid}{'+''.join(r'\draw[gridline] '+path(t['vertices'])+';' for t in board['triangles'])+'}')
for state in board['tilings']:
 name=state['label']
 lines.append(r'\newcommand{\Tiling'+name+'}{'+''.join(r'\draw[tile] '+path(t['vertices'])+';' for t in state['tiles'])+'}')
 pts=state['path_midpoints']
 lines.append(r'\newcommand{\Path'+name+'}{'+''.join(r'\draw[-{Stealth[length=4pt]},line width=1.2pt,dashed] '+point(a)+'--'+point(b)+';' for a,b in zip(pts,pts[1:]))+'}')
# Explicit attainable optimum in T3: three lozenges plus three up triangles.
commands=[]
for i,j in [(0,0),(1,0),(0,1)]:
 vs=[(i,j),(i+1,j),(i+1,j+1),(i,j+1)]
 commands.append(r'\draw[tile,fill=white] '+path(vs)+';')
 commands.append(r'\node[font=\small] at '+point((i+.5,j+.5))+' {B};')
for i,j in [(2,0),(1,1),(0,2)]:
 vs=[(i,j),(i+1,j),(i,j+1)]
 commands.append(r'\draw[tile,fill=black!12] '+path(vs)+';')
 commands.append(r'\node[font=\small] at '+point((i+1/3,j+1/3))+' {G};')
lines.append(r'\newcommand{\TriangleSolution}{'+''.join(commands)+'}')
# Same minimum green count, smaller total count: one chevron, one blue, three greens.
commands=[r'\draw[tile,fill=white] '+path([(1,0),(2,0),(2,1),(1,2),(0,2),(1,1)])+';',
          r'\node[font=\small] at '+point((1.45,1))+' {P};',
          r'\draw[tile,fill=white] '+path([(0,0),(1,0),(1,1),(0,1)])+';',
          r'\node[font=\small] at '+point((.5,.5))+' {B};']
for i,j in [(0,1),(0,2),(2,0)]:
 vs=[(i,j),(i+1,j),(i,j+1)]
 commands.append(r'\draw[tile,fill=black!12] '+path(vs)+';')
 commands.append(r'\node[font=\small] at '+point((i+1/3,j+1/3))+' {G};')
lines.append(r'\newcommand{\TrianglePurpleSolution}{'+''.join(commands)+'}')
# Balanced but impossible six-cell reserve, with cell names from the notes.
reserve=[('A',[(0,0),(1,0),(0,1)]),('B',[(1,0),(2,0),(1,1)]),('C',[(0,1),(1,1),(0,2)]),('D',[(1,1),(1,0),(0,1)]),('E',[(0,2),(0,1),(-1,2)]),('F',[(1,2),(1,1),(0,2)])]
commands=[]
for name,vs in reserve:
 commands.append(r'\draw[tile] '+path(vs)+';')
 center=tuple(sum(v[k] for v in vs)/3 for k in (0,1))
 commands.append(r'\node[font=\bfseries\small] at '+point(center)+' {'+name+'};')
lines.append(r'\newcommand{\Bottleneck}{'+''.join(commands)+'}')
(here/'tilings.tex').write_text('\n'.join(lines)+'\n')
print('Generated exact TikZ geometry for six tilings, paths, and solution diagrams.')
