#!/usr/bin/env python3
"""Generate extension-only TikZ from independently checked geometry and counts."""
import json
from math import atan2, sqrt
from pathlib import Path

here = Path(__file__).resolve().parent
plans = here.parents[2] / 'plans'
matching = json.loads((plans / 'week-01-extension-matching.json').read_text())
large = json.loads((plans / 'week-01-extension-checks.json').read_text())

def xy(p):
    return p[0] + p[1]/2, p[1]*sqrt(3)/2

def point(p):
    return '({:.9f},{:.9f})'.format(*xy(p))

def path(vertices):
    return '--'.join(map(point, vertices)) + '--cycle'

def center(vertices):
    return tuple(sum(p[k] for p in vertices)/len(vertices) for k in (0,1))

def macro(name, commands):
    return '\\newcommand{\\' + name + '}{' + ''.join(commands) + '}'

lines = ['% Generated by generate-extensions.py; one coordinate unit = one small edge.']
cells = {c['label']: c for c in matching['cells']}
board = []
for c in cells.values():
    board += [r'\draw[gridline] ' + path(c['vertices']) + ';',
              r'\node[font=\small] at ' + point(center(c['vertices'])) + ' {' + c['label'] + '};']
board += [r'\draw[outline] ' + path(matching['boundary']) + ';']
lines.append(macro('ExtensionMatchingBoard', board))
solution = []
for a,b in matching['optimal_blue_pairs']:
    vertices = set(map(tuple, cells[a]['vertices'])) | set(map(tuple, cells[b]['vertices']))
    c = center(vertices)
    cx, cy = xy(c)
    vs = sorted(vertices, key=lambda p: atan2(xy(p)[1]-cy, xy(p)[0]-cx))
    solution.append(r'\draw[tile,fill=white] ' + path(vs) + ';')
    solution.append(r'\node[font=\small] at ' + point(c) + ' {' + a + '+' + b + '};')
for name in matching['green_cells']:
    vs = cells[name]['vertices']
    solution.append(r'\draw[tile,fill=black!15] ' + path(vs) + ';')
    solution.append(r'\node[font=\small] at ' + point(center(vs)) + ' {' + name + '};')
solution.append(r'\draw[outline] ' + path(matching['boundary']) + ';')
lines.append(macro('ExtensionMatchingSolution', solution))
board = [r'\draw[gridline] ' + path(t['vertices']) + ';' for t in large['triangles']]
board += [r'\draw[outline] ' + path(large['polygon']) + ';', r'\draw[line width=2pt] (0,0)--(1,0);']
lines.append(macro('ExtensionLargeBoard', board))
start = next(t for t in large['tilings'] if t['word']=='RRRLLL')
lines.append(macro('ExtensionTilingStart', [r'\draw[tile] ' + path(t['vertices']) + ';' for t in start['tiles']] + [r'\draw[line width=2pt] (0,0)--(1,0);']))
lines.append(macro('ExtensionPathStart', [r'\draw[-{Stealth[length=4pt]},line width=1.2pt,dashed] ' + point(a) + '--' + point(b) + ';' for a,b in zip(start['path_midpoints'], start['path_midpoints'][1:])]))

rows = large['route_recurrence']
assert len(rows) == 20 and rows[-1]['routes'] == 42
def record(r):
    return '$(' + ','.join(map(str, r['state'])) + ')$'
for name, answers in [('ExtensionRouteTableBlank', False), ('ExtensionRouteTableAnswers', True)]:
    tab = [r'\begingroup\renewcommand{\arraystretch}{1.14}\begin{tabular}{c|c@{\hspace{.65in}}c|c}',
           r'\textbf{Record}&\textbf{Routes}&\textbf{Record}&\textbf{Routes}\\\hline ']
    def value(r):
        if answers or r['state'] in [[0,0,0],[1,0,0],[2,1,0]]:
            return str(r['routes'])
        return r'\rule{.50in}{.35pt}'
    for a,b in zip(rows[:10], rows[10:]):
        tab.append(record(a) + '&' + value(a) + '&' + record(b) + '&' + value(b) + r'\\')
    tab.append(r'\end{tabular}\endgroup')
    lines.append(macro(name, tab))
(here / 'extensions-geometry.tex').write_text('\n'.join(lines) + '\n')
print('Generated matching board, H133 mat and ribbon, and route-count tables.')
