#!/usr/bin/env python3
"""Write full-size blank mats and small facilitator diagrams from checked data."""
import json
from math import sqrt
from pathlib import Path

here = Path(__file__).resolve().parent
data = json.loads((here/'../../../../plans/week-01-k1-shape-checks.json').resolve().read_text())


def path(poly):
    return '--'.join('({:.9f},{:.9f})'.format(u+v/2,v*sqrt(3)/2) for u,v in poly)+'--cycle'


lines = ['% Generated by generate-k1-geometry.py. One coordinate unit = one small edge.']
for name,shape in data.items():
    lines.append(r'\newcommand{\K'+name+r'Path}{'+path(shape['polygon'])+'}')
    for color,solutions in shape['solutions'].items():
        if not solutions:
            continue
        lines.append(r'\newcommand{\K'+name+color.title()+r'Solution}{'+''.join(
            r'\draw[tile,fill=black!6] '+path(poly)+';' for poly in solutions[0])+'}')
(here/'k1-geometry.tex').write_text('\n'.join(lines)+'\n')
print('Generated eight K–1 outlines and checked solution diagrams.')
