"""Week 12 (Catalan bijections) math check: independent combinatorics.

Written for this review. It does not import the packet's builders or checkers.
Three objects are generated independently of one another:
  * all perfect matchings of 1..2n (brute force), filtered by an interleaving test;
  * all U/D words of length 2n (brute force over 2^(2n) strings), filtered by prefix heights;
  * ordered rooted trees, generated by compositions of the root's children
    (not by the first-return split the guide uses).
Then every answer the student pages imply and every claim the guides make is
recomputed.  Run: python3 catalan.py > catalan.out
"""
import itertools
from functools import lru_cache

FAIL = []


def check(name, ok, detail=''):
    print(('PASS ' if ok else 'FAIL ') + name + ((': ' + str(detail)) if detail != '' else ''))
    if not ok:
        FAIL.append(name)


# ------------------------------------------------------------------ matchings
def all_matchings(pts):
    pts = list(pts)
    if not pts:
        yield ()
        return
    a = pts[0]
    for i in range(1, len(pts)):
        rest = pts[1:i] + pts[i + 1:]
        for m in all_matchings(rest):
            yield tuple(sorted(((a, pts[i]),) + m))


def crosses(e, f):
    (a, b), (c, d) = sorted(e), sorted(f)
    return a < c < b < d or c < a < d < b


def noncrossing(m):
    return not any(crosses(e, f) for e, f in itertools.combinations(m, 2))


def nc_matchings(N):
    """Noncrossing perfect matchings of points 1..N (fixed labels)."""
    if N % 2:
        return []
    return [m for m in all_matchings(range(1, N + 1)) if noncrossing(m)]


def code_of_matching(m, N):
    first = {min(e) for e in m}
    return ''.join('U' if i in first else 'D' for i in range(1, N + 1))


def fmt(m):
    return '|'.join(f'{a}{b}' if b < 10 else f'{a}-{b}' for a, b in sorted(m))


# ------------------------------------------------------------------ words
def heights(w):
    h = [0]
    for c in w:
        h.append(h[-1] + (1 if c == 'U' else -1))
    return h


def is_dyck(w):
    h = heights(w)
    return min(h) >= 0 and h[-1] == 0


def dyck_words(n):
    return sorted(''.join(t) for t in itertools.product('UD', repeat=2 * n) if is_dyck(''.join(t)))


def matchings_with_code(w):
    """Every noncrossing matching of 1..len(w) whose U/D code is w (brute force, no stack rule)."""
    return [m for m in nc_matchings(len(w)) if code_of_matching(m, len(w)) == w]


# ------------------------------------------------------------------ ordered trees
@lru_cache(None)
def trees(n):
    """Ordered rooted trees with n edges, as nested tuples of children.
    Generated by choosing a composition of n into root-branch sizes (k_i+1)."""
    if n == 0:
        return ((),)
    out = []

    def comps(m):
        if m == 0:
            yield ()
            return
        for first in range(1, m + 1):
            for rest in comps(m - first):
                yield (first,) + rest

    for comp in comps(n):
        for kids in itertools.product(*[trees(s - 1) for s in comp]):
            out.append(tuple(kids))
    return tuple(out)


def walk(t):
    return ''.join('U' + walk(c) + 'D' for c in t)


def leaves(t):
    if not t:
        return 1
    return sum(leaves(c) for c in t)


def depth(t):
    return 0 if not t else 1 + max(depth(c) for c in t)


def tree_from_code_bruteforce(w):
    """All trees with len(w)/2 edges whose walk is w (search, not the guide's rule)."""
    return [t for t in trees(len(w) // 2) if walk(t) == w]


def nesting_depth(m):
    best = 0
    for e in m:
        d = 1 + sum(1 for f in m if f != e and min(f) < min(e) and max(e) < max(f))
        best = max(best, d)
    return best


def peaks(w):
    return sum(1 for i in range(len(w) - 1) if w[i:i + 2] == 'UD')


def returns(w):
    return sum(1 for h in heights(w)[1:] if h == 0)


print('== Catalan counts from three independent generators')
counts = {}
for n in range(0, 7):
    M = nc_matchings(2 * n)
    W = dyck_words(n)
    T = trees(n)
    counts[n] = (len(M), len(W), len(T))
    check(f'n={n}: matchings={len(M)} dyck={len(W)} trees={len(T)} all equal', len(M) == len(W) == len(T))
    # pairing -> code is a bijection onto Dyck words
    codes = sorted(code_of_matching(m, 2 * n) for m in M)
    check(f'n={n}: pairing codes are distinct and are exactly the Dyck words', codes == W)
    # tree -> walk is a bijection onto Dyck words
    walks = sorted(walk(t) for t in T)
    check(f'n={n}: tree walks are distinct and are exactly the Dyck words', walks == W)
    # statistics
    if n >= 1:
        ok = all(peaks(walk(t)) == leaves(t) for t in T)
        check(f'n={n}: peaks (UD) = leaves for every tree', ok)
        ok = all(max(heights(walk(t))) == depth(t) for t in T)
        check(f'n={n}: max height = tree depth for every tree', ok)
        ok = all(returns(walk(t)) == len(t) for t in T)
        check(f'n={n}: returns to zero = number of root children', ok)
        ok = all(max(heights(code_of_matching(m, 2 * n))) == nesting_depth(m) for m in M)
        check(f'n={n}: max height = deepest arc nesting for every pairing', ok)
check('counts are 1,1,2,5,14,42,132', [counts[n][0] for n in range(7)] == [1, 1, 2, 5, 14, 42, 132])

# Recurrence values printed in the guide
C = [counts[n][0] for n in range(7)]
check('C(4)=5+2+2+5', [C[i] * C[3 - i] for i in range(4)] == [5, 2, 2, 5] and C[4] == 14)
check('C(5)=14+5+4+5+14', [C[i] * C[4 - i] for i in range(5)] == [14, 5, 4, 5, 14] and C[5] == 42)
check('C(6)=42+14+10+10+14+42', [C[i] * C[5 - i] for i in range(6)] == [42, 14, 10, 10, 14, 42] and C[6] == 132)

# Uniqueness of the inverse (brute force over all noncrossing matchings, no stack rule)
for n in range(1, 6):
    ok = all(len(matchings_with_code(w)) == 1 for w in dyck_words(n))
    check(f'n={n}: every Dyck word is the code of exactly one noncrossing pairing', ok)
    ok = all(len(tree_from_code_bruteforce(w)) == 1 for w in dyck_words(n))
    check(f'n={n}: every Dyck word is the walk of exactly one ordered tree', ok)
# Every U/D string of length 2n that is a code is a Dyck word (so "rules" are exactly the Dyck conditions)
for n in range(1, 6):
    allcodes = {code_of_matching(m, 2 * n) for m in all_matchings(range(1, 2 * n + 1))}
    check(f'n={n}: codes of ALL pairings (crossing allowed) are still exactly Dyck words', sorted(allcodes) == dyck_words(n))

print()
print('== K-1')
four = nc_matchings(4)
check('four dots: two pairings 12|34 and 14|23', sorted(fmt(m) for m in four) == ['12|34', '14|23'], [fmt(m) for m in four])
check('four dots with crossings allowed: three pairings', len(list(all_matchings(range(1, 5)))) == 3)
six = nc_matchings(6)
print('six-dot pairings:', [fmt(m) for m in six])
check('P1/P2: five six-dot pairings 12|34|56, 12|36|45, 14|23|56, 16|23|45, 16|25|34',
      sorted(fmt(m) for m in six) == ['12|34|56', '12|36|45', '14|23|56', '16|23|45', '16|25|34'])
split6 = {p: sum(1 for m in six if (1, p) in m) for p in range(2, 7)}
check('P2 guide: partner of 1 is 2,4,6 giving 2,1,2', split6 == {2: 2, 3: 0, 4: 1, 5: 0, 6: 2}, split6)
eight = nc_matchings(8)
for chord, expect in [((1, 4), ['14|23|56|78', '14|23|58|67']), ((1, 6), ['16|23|45|78', '16|25|34|78']),
                      ((1, 3), []), ((1, 5), [])]:
    got = sorted(fmt(m) for m in eight if chord in m)
    check(f'P3: completions of {chord}', got == expect, got)
# trapped counts on each side
for a, b in [(1, 3), (1, 5)]:
    inside = b - a - 1
    outside = 8 - 2 - inside
    print(f'  chord {a}{b}: {inside} dot(s) on one side, {outside} on the other')
split8 = {p: sum(1 for m in eight if (1, p) in m) for p in range(2, 9)}
check('P4: 14 eight-dot pairings, partner of 1 = 2,4,6,8 gives 5,2,2,5',
      len(eight) == 14 and split8 == {2: 5, 3: 0, 4: 2, 5: 0, 6: 2, 7: 0, 8: 5}, split8)
# guide K-1 P4 hint: "compare only the partners at a single numbered dot to check for duplicates"
for d in range(1, 9):
    groups = {}
    for m in eight:
        partner = [b if a == d else a for a, b in m if d in (a, b)][0]
        groups.setdefault(partner, []).append(m)
    same = sum(len(g) * (len(g) - 1) // 2 for g in groups.values())
    print(f'  dot {d}: partner groups {sorted(len(g) for g in groups.values())}; {same} pairs of DIFFERENT pairings agree at this dot')
ex_a, ex_b = ((1, 2), (3, 4), (5, 6), (7, 8)), ((1, 2), (3, 8), (4, 5), (6, 7))
check('K-1 P4 hint is not a duplicate test: 12|34|56|78 and 12|38|45|67 agree at dot 1 but differ',
      ex_a in eight and ex_b in eight and ex_a != ex_b)
agree_max = max(sum(1 for d in range(1, 9) if [e for e in a if d in e] == [e for e in b if d in e])
                for a, b in itertools.combinations(eight, 2))
print(f'  two different eight-dot pairings can agree at up to {agree_max} dots')
for N in [10, 3, 4, 5, 6, 7]:
    total = list(all_matchings(range(1, N + 1))) if N % 2 == 0 else []
    nc = nc_matchings(N)
    possible = len(nc) > 0
    check(f'P5: {N} dots possible={possible} (expected {N % 2 == 0})', possible == (N % 2 == 0))
    if possible:
        adj = tuple((i, i + 1) for i in range(1, N, 2))
        check(f'P5: {N} dots, adjacent pairs {fmt(adj)} is a noncrossing pairing', adj in nc)


def has_circular_neighbors(m, N):
    return any(b - a == 1 or (a, b) == (1, N) for a, b in m)


for N in [4, 6, 8, 10, 12]:
    nc = nc_matchings(N)
    check(f'P6: every {N}-dot noncrossing pairing joins two circular neighbours',
          all(has_circular_neighbors(m, N) for m in nc))
    # stronger: at least two neighbour pairs for N>=4
    check(f'  ({N} dots: each has at least two such pairs)', all(sum(1 for a, b in m if b - a == 1 or (a, b) == (1, N)) >= 2 for m in nc))
# With crossings allowed, 8 dots CAN avoid neighbours (shows the noncrossing rule matters)
cross_ok = [m for m in all_matchings(range(1, 9)) if not has_circular_neighbors(m, 8)]
print(f'  (with crossings allowed, {len(cross_ok)} eight-dot pairings avoid neighbours, e.g. {fmt(cross_ok[0])})')

print()
print('== Grades 2-3')
ex10 = ((1, 4), (2, 3), (5, 10), (6, 7), (8, 9))
check('example ten dots 14|23|5-10|67|89 is noncrossing', noncrossing(ex10))
check('P2 example: 12|36|45|78 -> UDUUDDUD', code_of_matching(((1, 2), (3, 6), (4, 5), (7, 8)), 8) == 'UDUUDDUD')
for m, w, h in [(((1, 6), (2, 5), (3, 4)), 'UUUDDD', [0, 1, 2, 3, 2, 1, 0]),
                (((1, 4), (2, 3), (5, 6)), 'UUDDUD', [0, 1, 2, 1, 0, 1, 0]),
                (((1, 2), (3, 4), (5, 6)), 'UDUDUD', [0, 1, 0, 1, 0, 1, 0])]:
    check(f'P2: {fmt(m)} -> {w}, heights {h}, max height <= 3 (grid has 3 rows)',
          code_of_matching(m, 6) == w and heights(w) == h and max(h) <= 3)
for w, expect in [('UUDUDD', '16|23|45'), ('UDUUDD', '12|36|45'), ('UUDDUUDD', '14|23|58|67'), ('UUUDUDDD', '18|27|34|56')]:
    got = [fmt(m) for m in matchings_with_code(w)]
    check(f'P3: {w} has exactly one noncrossing pairing {expect}', got == [expect], got)
    crossing = [fmt(m) for m in all_matchings(range(1, len(w) + 1)) if code_of_matching(m, len(w)) == w and not noncrossing(m)]
    print(f'  ({w}: {len(crossing)} crossing pairing(s) share this code)')
check('P4: five Dyck paths with three U and three D', len(dyck_words(3)) == 5, dyck_words(3))
for w, valid, expect in [('UUUDDUDD', True, '18|25|34|67'), ('UDDUUDUD', False, None),
                         ('UUDUDUDD', True, '18|23|45|67'), ('UUUUDDUD', False, None)]:
    ms = [fmt(m) for m in matchings_with_code(w)]
    anym = [fmt(m) for m in all_matchings(range(1, 9)) if code_of_matching(m, 8) == w]
    check(f'P5: {w} valid={valid}', is_dyck(w) == valid and (ms == [expect] if valid else (ms == [] and anym == [])), (ms, len(anym)))
h = heights('UDDUUDUD')
check('P5 guide: UDDUUDUD has height -1 after letter 3', h[3] == -1 and min(h[:3]) >= 0, h)
check('P5 guide: UUUUDDUD has five U, three D, ends at height 2', 'UUUUDDUD'.count('U') == 5 and heights('UUUUDDUD')[-1] == 2)
check('P6: 14 eight-dot pairings; 16 rows printed', len(eight) == 14)

print()
print('== Grades 4-5')
check('example five-edge tree: root has two children, left has two leaf children, right has one leaf',
      tuple(t for t in trees(5) if walk(t) == 'UUDUDDUUDD') == ((((), ()), ((),)),))
check('walk example: two-edge fork has code UDUD', walk(((), ())) == 'UDUD')
t3 = trees(3)
check('P1: five three-edge trees', len(t3) == 5, sorted(walk(t) for t in t3))
by_root = {}
for t in t3:
    by_root[len(t)] = by_root.get(len(t), 0) + 1
check('guide p.6: split by number of root children 1,2,3 -> 2,2,1', by_root == {1: 2, 2: 2, 3: 1}, by_root)
printed_p2 = {'path of four edges': (((((),),),),),
              'star of four leaves': ((), (), (), ()),
              'left child with two leaves, right leaf': (((), ()), ()),
              'left leaf, right chain of three edges': ((), (((),),))}
for name, t in printed_p2.items():
    print(f'  P2 {name}: {walk(t)} ({len(walk(t))} letters)')
check('P2 codes UUUUDDDD, UDUDUDUD, UUDUDDUD, UDUUUDDD',
      [walk(t) for t in printed_p2.values()] == ['UUUUDDDD', 'UDUDUDUD', 'UUDUDDUD', 'UDUUUDDD'])
for w, expect in [('UUDDUD', (((),), ())), ('UDUUDD', ((), ((),))), ('UUDUDUDD', (((), (), ()),)),
                  ('UUUDDUDD', ((((),), ()),))]:
    got = tree_from_code_bruteforce(w)
    check(f'P3: {w} describes exactly one tree {expect}', got == [expect], got)
for w, valid in [('UUUUDDDD', True), ('UUDDDUUD', False), ('UDUDUUDD', True),
                 ('UUDUDUDU', False), ('UUUDUDDD', True), ('DUUUDDUD', False)]:
    trees_found = tree_from_code_bruteforce(w) if w.count('U') == w.count('D') else []
    check(f'P4: {w} valid={valid}', is_dyck(w) == valid and (len(trees_found) == 1) == valid)
for w, at in [('UUDDDUUD', 5), ('DUUUDDUD', 1)]:
    h = heights(w)
    first = next(i for i, x in enumerate(h) if x < 0)
    check(f'P4 guide: {w} first goes below zero at letter {at}', first == at, first)
check('P4 guide: UUDUDUDU finishes at height 2', heights('UUDUDUDU')[-1] == 2)
check('P5: 14 four-edge trees; 16 roots printed', len(trees(4)) == 14)
check('P6: 42 five-edge and 132 six-edge trees', len(trees(5)) == 42 and len(trees(6)) == 132)

# first-return split is a bijection (independent check of the guide's proof)
for n in range(1, 7):
    W = dyck_words(n)
    built = sorted('U' + p + 'D' + q for i in range(n) for p in dyck_words(i) for q in dyck_words(n - 1 - i))
    check(f'n={n}: U P D Q (first return) builds each Dyck word exactly once', built == W)
# tree split: first child subtree + remaining branches
for n in range(1, 7):
    pairs = sorted((walk(t[0]), walk(t[1:])) for t in trees(n))
    check(f'n={n}: (first child subtree, rest) is a bijection to pairs of smaller trees',
          len(set(pairs)) == len(pairs) == sum(len(trees(i)) * len(trees(n - 1 - i)) for i in range(n)))

print()
print('== Return visit')


def unlike_pairings(word):
    N = len(word)
    return [m for m in nc_matchings(N) if all(word[a - 1] != word[b - 1] for a, b in m)]


for word, expect in [('RBRBRB', ['12|34|56', '12|36|45', '14|23|56', '16|23|45', '16|25|34']),
                     ('RRRBBB', ['16|25|34']), ('RRBRBB', ['16|23|45', '16|25|34'])]:
    got = sorted(fmt(m) for m in unlike_pairings(word))
    check(f'RV P1: {word} unlike pairings {got}', got == expect)
# existence iff equal counts (all cyclic words up to length 10)
ok = True
for N in range(2, 11, 2):
    for t in itertools.product('RB', repeat=N):
        w = ''.join(t)
        if (len(unlike_pairings(w)) > 0) != (w.count('R') == w.count('B')):
            ok = False
check('RV guide: unlike noncrossing pairing exists iff R and B counts agree (all words, N<=10)', ok)


def ceil_count(n, c):
    return sum(1 for w in dyck_words(n) if max(heights(w)) <= c)


for n in range(1, 8):
    check(f'RV: ceiling-2 paths with {n} pairs = 2^(n-1) = {2 ** (n - 1)}', ceil_count(n, 2) == 2 ** (n - 1), ceil_count(n, 2))
check('RV guide: ceilings 1,2,3,4 with four pairs give 1,8,13,14',
      [ceil_count(4, c) for c in (1, 2, 3, 4)] == [1, 8, 13, 14])
listed = ['UDUDUDUD', 'UUDDUDUD', 'UDUUDDUD', 'UDUDUUDD', 'UUDDUUDD', 'UUDUDDUD', 'UDUUDUDD', 'UUDUDUDD']
check('RV guide p.4: the eight listed ceiling-2 paths are exactly the right set',
      sorted(listed) == sorted(w for w in dyck_words(4) if max(heights(w)) <= 2))
check('RV guide: ceiling 3 excludes only UUUUDDDD',
      [w for w in dyck_words(4) if max(heights(w)) > 3] == ['UUUUDDDD'])
check('RV P3: ceiling 2, five pairs -> 16', ceil_count(5, 2) == 16)


def blocks_ok(n):
    # each ground block of a ceiling-2 path is U (UD)^k D
    for w in dyck_words(n):
        if max(heights(w)) > 2:
            continue
        h = heights(w)
        cuts = [i for i, x in enumerate(h) if x == 0]
        for a, b in zip(cuts, cuts[1:]):
            blk = w[a:b]
            r = (b - a) // 2
            if blk != 'U' + 'UD' * (r - 1) + 'D':
                return False
    return True


check('RV guide: every ceiling-2 ground block is U (UD)^(r-1) D (n<=7)', all(blocks_ok(n) for n in range(1, 8)))


# swap graph: a move swaps adjacent unlike letters and must stay a Dyck path
def neighbours(w):
    out = []
    for i in range(len(w) - 1):
        if w[i] != w[i + 1]:
            v = w[:i] + w[i + 1] + w[i] + w[i + 2:]
            if is_dyck(v):
                out.append(v)
    return out


def bfs(src, n):
    dist = {src: 0}
    q = [src]
    for x in q:
        for y in neighbours(x):
            if y not in dist:
                dist[y] = dist[x] + 1
                q.append(y)
    return dist


def score(w):
    n = len(w) // 2
    m = heights('U' * n + 'D' * n)
    return sum(a - b for a, b in zip(m, heights(w))) // 2


def inversions(w):
    return sum(1 for i in range(len(w)) for j in range(i + 1, len(w)) if w[i] == 'D' and w[j] == 'U')


target = 'UUUUDDDD'
D = bfs(target, 4)
check('RV: swap graph on four-pair Dyck paths is connected', len(D) == 14)
for s, d in [('UDUDUDUD', 6), ('UUDDUUDD', 4), ('UUUDUDDD', 1)]:
    check(f'RV P4: {s} is {d} moves from {target}', D[s] == d, D[s])
for n in range(1, 7):
    Dn = bfs('U' * n + 'D' * n, n)
    ok = all(Dn[w] == score(w) == inversions(w) for w in dyck_words(n))
    check(f'RV guide: distance to mountain = half the height gap = D-before-U count (n={n})', ok)
route = ['UDUDUDUD', 'UUDDUDUD', 'UUDUDDUD', 'UUUDDDUD', 'UUUDDUDD', 'UUUDUDDD', 'UUUUDDDD']
check('RV guide: printed 6-move route is legal, one swap per arrow',
      all(b in neighbours(a) for a, b in zip(route, route[1:])), route)
route2 = ['UUDDUUDD', 'UUDUDUDD', 'UUUDDUDD', 'UUUDUDDD', 'UUUUDDDD']
check('RV guide: printed 4-move route is legal', all(b in neighbours(a) for a, b in zip(route2, route2[1:])))
check('RV guide: UUUDUDDD -> UUUUDDDD by swapping its middle DU', 'UUUUDDDD' in neighbours('UUUDUDDD'))
check('RV guide: alternating path height gap sums to twelve',
      sum(a - b for a, b in zip(heights(target), heights('UDUDUDUD'))) == 12)
# example on page 4
check('RV example: UDUUDD with letters 2,3 swapped is UUDUDD', 'UDUUDD'[0] + 'UD' + 'UDUUDD'[3:] == 'UUDUDD' and 'UDUUDD'[1:3] == 'DU')
# every swap changes the score by exactly one
ok = all(abs(score(a) - score(b)) == 1 for n in range(1, 6) for a in dyck_words(n) for b in neighbours(a))
check('RV guide: every legal swap changes the score by exactly one (n<=5)', ok)

# the guide's caution: the mountain score alone does not give the distance between two arbitrary paths
for n in range(3, 6):
    W = dyck_words(n)
    allok = True
    score_fails = 0
    for a in W:
        Da = bfs(a, n)
        for b in W:
            l1 = sum(abs(x - y) for x, y in zip(heights(a), heights(b))) // 2
            allok &= Da[b] == l1
            score_fails += Da[b] != abs(score(a) - score(b))
    check(f'RV extension (n={n}): distance between any two paths = half the summed height gaps; '
          f'{score_fails} ordered pairs where the score difference is not the distance', allok and score_fails > 0)
check('RV: ceiling-3 counts for n=1..6 are 1,2,5,13,34,89', [ceil_count(n, 3) for n in range(1, 7)] == [1, 2, 5, 13, 34, 89])

print()
print('FAILED:', FAIL if FAIL else 'none')
