#!/usr/bin/env python3
"""Portable ReportLab source for the Week 27 adult guide. Rebuild: python3 build_guide.py."""
from pathlib import Path
import json
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Flowable, KeepTogether
from reportlab.lib.pagesizes import letter
ROOT=Path(__file__).resolve().parent
from portable_fonts import font_directory
FONTS=font_directory('Liberation Sans',[f'LiberationSans-{v}.ttf' for v in ['Regular','Bold','Italic','BoldItalic']],'LIBERATION_FONT_DIR')
D=json.loads((ROOT/'math-checks.json').read_text())
OUT=ROOT.parent/'build'/'facilitator-guide.pdf'
for suffix, file in [('', 'Regular'),('-Bold','Bold'),('-Italic','Italic'),('-BoldItalic','BoldItalic')]:
 pdfmetrics.registerFont(TTFont('Guide'+suffix,str(FONTS/('LiberationSans-'+file+'.ttf'))))
pdfmetrics.registerFontFamily('Guide',normal='Guide',bold='Guide-Bold',italic='Guide-Italic',boldItalic='Guide-BoldItalic')
INK=colors.HexColor('#20343E');TEAL=colors.HexColor('#146878');LIGHT=colors.HexColor('#EAF2F4');GRAY=colors.HexColor('#52636A')
ST=getSampleStyleSheet()
ST.add(ParagraphStyle(name='BodyX',fontName='Guide',fontSize=10.1,leading=14.3,textColor=INK,spaceAfter=7))
ST.add(ParagraphStyle(name='SmallX',fontName='Guide',fontSize=8.7,leading=11.8,textColor=INK,spaceAfter=5))
ST.add(ParagraphStyle(name='TitleX',fontName='Guide-Bold',fontSize=23,leading=27,textColor=TEAL,spaceAfter=10))
ST.add(ParagraphStyle(name='HeadX',fontName='Guide-Bold',fontSize=16,leading=20,textColor=TEAL,spaceAfter=10))
ST.add(ParagraphStyle(name='SubX',fontName='Guide-Bold',fontSize=11.7,leading=15,textColor=INK,spaceBefore=7,spaceAfter=5))
ST.add(ParagraphStyle(name='CellX',fontName='Guide',fontSize=9,leading=12,textColor=INK))
ST.add(ParagraphStyle(name='HintX',fontName='Guide',fontSize=9.7,leading=13.7,textColor=INK,backColor=LIGHT,borderPadding=7,spaceBefore=5,spaceAfter=11))
S=[]
def p(s,style='BodyX'):return Paragraph(s,ST[style])
def add(s,style='BodyX'):S.append(p(s,style))
def heading(s):add(s,'HeadX')
def sub(s):add(s,'SubX')
def hint(s):add('<b>Held hint.</b> '+s,'HintX')
def table(rows,widths=None,head=True,small=False):
 data=[[p(str(v),'SmallX' if small else 'CellX') for v in row] for row in rows]
 t=Table(data,colWidths=widths,hAlign='LEFT',repeatRows=1 if head else 0)
 t.setStyle(TableStyle([('FONTNAME',(0,0),(-1,-1),'Guide'),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5),('ROWBACKGROUNDS',(0,1 if head else 0),(-1,-1),[colors.white,colors.HexColor('#F5F7F8')]),('BACKGROUND',(0,0),(-1,0),LIGHT if head else colors.white),('LINEBELOW',(0,-1),(-1,-1),.5,colors.HexColor('#BDCED3'))]))
 S.append(t);S.append(Spacer(1,8))
def page():S.append(PageBreak())
def profiles(key):
 d=D[key];n=len(d['left']); rows=[['Circles: first to last','Squares: first to last']]
 for (a,x),(b,y) in zip(d['left'].items(),d['right'].items()):rows.append([a+': '+ ' > '.join(x),b+': '+' > '.join(y)])
 table(rows,[264,264])
def blockers_table(key,all_blockers=False):
 rows=[['Candidate pairing','Blocking pair(s), or stable']]
 for r in D[key]['candidates']:
  rows.append([r['matching'].replace('/',' / '),', '.join(r['blockers']) if all_blockers else (r['blockers'][0] if r['blockers'] else '<b>Stable</b>')])
 table(rows,[230,298])
class Matchings(Flowable):
 def __init__(self,matchings,left='AB',right='XY',titles=None,width=528,height=None,blocks=None):
  Flowable.__init__(self);self.ms=matchings;self.left=left;self.right=right;self.titles=titles or matchings;self.width=width;self.height=height or (45+len(left)*30);self.blocks=blocks or [None]*len(matchings)
 def draw(self):
  c=self.canv;span=self.width/len(self.ms)
  for k,code in enumerate(self.ms):
   x=k*span;lx=x+span*.25;rx=x+span*.75;top=self.height-38;step=min(29,(self.height-50)/max(1,len(self.left)-1))
   c.setFillColor(INK);c.setFont('Guide-Bold',9.2);c.drawCentredString(x+span/2,self.height-10,self.titles[k])
   m=dict(pair.split(':') if ':' in pair else tuple(pair) for pair in code.split('/'))
   c.setStrokeColor(INK);c.setLineWidth(1.1)
   for a,b in m.items():c.line(lx,top-self.left.index(a)*step,rx,top-self.right.index(b)*step)
   if self.blocks[k]:
    a,b=self.blocks[k];c.setStrokeColor(TEAL);c.setDash(3,2);c.setLineWidth(2);c.line(lx,top-self.left.index(a)*step,rx,top-self.right.index(b)*step);c.setDash()
   for i,a in enumerate(self.left):
    cy=top-i*step;c.setFillColor(colors.white);c.setStrokeColor(INK);c.circle(lx,cy,10,stroke=1,fill=1);c.setFillColor(INK);c.setFont('Guide-Bold',10);c.drawCentredString(lx,cy-3.3,a)
   for i,b in enumerate(self.right):
    cy=top-i*step;c.setFillColor(colors.white);c.setStrokeColor(INK);c.rect(rx-10,cy-10,20,20,stroke=1,fill=1);c.setFillColor(INK);c.drawCentredString(rx,cy-3.3,b)
  c.setStrokeColor(INK)
def diagram(*args,**kwargs):S.append(Matchings(*args,**kwargs));S.append(Spacer(1,5))

def footer(c,doc):
 c.saveState();c.setFillColor(GRAY);c.setFont('Guide',8.3)
 c.drawString(42,25,'Bellingham Math Circle / Week 27 / Adult guide / Draft, unpiloted')
 c.drawRightString(570,25,str(doc.page));c.restoreState()

# 1
add('Week 27<br/>Pair everyone without a blocking pair','TitleX')
add('Facilitator guide for the current student packets','SubX')
add('<b>Draft / unpiloted / unscheduled library slot.</b> Week 27 is a library label, not a booked meeting or a claim that this is appropriate for every child. Prepared 2026-10-03. Upper Problem 2 now includes a small hold/release example.')
sub('The mathematical promise')
add('Two equal-sized sets rank every object on the other side, with no ties. A <b>blocking pair</b> is a circle and square not paired to one another that <b>both</b> rank each other ahead of their current partners. A stable pairing has no blocking pair. Stability need not mean first choices for everyone, a unique answer, or maximum total happiness.')
sub('A real prerequisite gate, especially for K-1')
add('Before choosing a packet, ask a child to read or point along a two-choice strip, keep track of the current pairs, and check <b>both sides</b> of a proposed switch. Use the first-page P-U panels to demonstrate one mutual wish and one one-sided wish. Participation requires understanding why only the first is a blocking pair. Grade alone does not establish readiness.')
add('A minimal K-1 introduction is to check one proposed pair against two fixed preference strips: does each prefer the switch? Let children move tokens and point; adults read. Stay with this concrete challenge while the two-sided check develops. Problems 1-2 then give a complete two-pair encounter; Problems 3-6 are readiness-dependent continuations, including a later visit. Do not rank real children.')
table([['Route','Prerequisites beyond the shared gate','Useful stopping point'],['K-1, 6 problems','Read aloud; recognize four labels; compare two ranks; later invent lists and justify impossibility. No arithmetic needed.','Problems 1-2 are a complete small encounter. Problems 3-6 are optional depth.'],['Grades 2-3, 5 problems','Track three or four pairs; record trials; organize all cases. An adult may read every strip.','Problems 1-3; choose 4 or 5 if the search remains engaging.'],['Grades 4-5, 6 problems','Track changing temporary holds and request history; reason about every possible run.','Problems 1-2 plus either counterexample 3 or proof 4-5. Problem 6 is independent depth.']],[85,286,157])
sub('Using this key')
add('K-1 and middle page 1 are example references; task pages retain one numbered problem each. Guide pages 3-5 cover K-1; pages 6-9 cover grades 2-3; pages 10-15 cover grades 4-5. Page 16 holds extensions; page 17 records sources and fidelity. Answers and diagrams are for adults. Offer one held hint only after children have tried their own approach.')
page()
#2
heading('Prepare, launch, and choose an hour')
sub('Separate full-size table materials are required')
add('For each participating table: four labeled circle tokens A-D and four labeled square tokens W-Z; eight complete preference strips with four rank positions; eight blank replacement strips; four removable links; sixteen small already-asked markers; paper and pencils. <b>Tokens and every strip icon must be at least 20 mm across.</b> Use removable labels or dry-erase cards; make each four-choice strip about 120 mm wide so the owner and four choices remain distinct.')
add('For two-pair work use A, B and X, Y; for three-pair work use A, B, C and X, Y, Z. Remove unused labels from <b>every</b> strip. Copy the exact profile for the selected problem, with rank 1 at the left. Check that every opposite-side label occurs once. Reset all strips and request markers between cases.')
add('The older student pages use compact <b>pencil-recording diagrams</b>, about 10-13 mm icons. They are not cut-out cards, work mats, or substitutes for the separate materials. K-1 task icons are about 20.1 mm at 100% scale; the example is a compact reference, but large table materials are still the default. Print chosen pages single-sided, US Letter, actual size. Do not shrink or fit to page.')
sub('Short shared launch, 4-5 minutes after free handling')
add('Use A: X > Y; B: X > Y; X: A > B; Y: A > B. Place AX and BY. Ask, "B would rather have X. Does X also want B more than A?" Point to both strips: no, so BX does not block. Now change the pairing to AY and BX without changing strips. A and X both want one another: they block. Demonstrate recording a pair as a line; crossing lines are allowed and carry no mathematical meaning. Let children check a second candidate themselves before separating routes.')
table([['Minutes','Flexible menu for three adult-led tables'],['0-5','Handle tokens; learn the circle/square convention. Keep lists fixed once an instance begins.'],['5-10','Shared two-sided demonstration and readiness check. Distribute only the chosen starting pages.'],['10-27','K-1: 1-2. Middle: 1-2 or 3. Older: 1 then 2. Give time to move cards and challenge candidates.'],['27-30','Brief movement break: stretch or carry artificial tokens; never rank children.'],['30-52','Continue a productive problem. K-1 may try 3-4; middle 3-5; older 3 or 4-5, with 6 for another route.'],['52-60','Invite one blocking-pair explanation and one stable example or conjecture. Record what actually happened.']],[64,464])
add('<b>Adult roles.</b> Current planning context is eleven children (KK11 / 3333 / 445) and three adults. Keep one adult anchored at each table; the non-mathematician parent can use the two-pair key. Older proof work benefits from a mathematician. Finishing pages is not the target. The schedule is a proposal, not classroom evidence.','SmallX')
page()
#3
heading('K-1 / Problems 1 and 2')
add('Read "can stay" as "stable." In a two-pair market there are only two perfect pairings: once A chooses X or Y, B is forced. Children can establish completeness by physically exhausting those two choices.')
diagram(['AX/BY','AY/BX'],titles=['Straight pairing: AX / BY','Crossed pairing: AY / BX'])
sub('Problem 1 / Circle every pairing that can stay')
table([['Case and exact strips','Answer and rejection witness'],['Top: A: XY; B: YX; X: AB; Y: BA.','Circle only AX / BY. All four have first choices. The crossed pairing has blockers AX and BY.'],['Bottom: A: XY; B: XY; X: AB; Y: AB.','Circle only AX / BY. AY / BX is blocked by AX. In AX / BY, B wants X, but X prefers A; Y wants A, but A prefers X.']],[264,264])
add('Here and below, XY in a strip means X first, Y second. It is not a pairing. A pairing such as AX / BY means A is with X and B is with Y.')
hint('If a child rejects a pairing because one piece is disappointed, place fingers on that piece and the desired partner. Ask each one the same question: "Which do you want more, your current partner or this one?" Both answers must favor the new pair.')
sub('Problem 2 / Draw every pairing that can stay')
table([['Case and exact strips','Complete answer'],['Top: A: XY; B: YX; X: BA; Y: AB.','Both AX / BY and AY / BX. In the straight pairing both circles get first choices. In the crossed pairing both squares get first choices. Either way, every possible new pair contains someone who will not switch.'],['Bottom: A: YX; B: XY; X: BA; Y: AB.','Only AY / BX. All four get first choices. The straight pairing has two blockers: AY and BX.']],[264,264])
hint('If only one answer is found, ask whether A has another possible partner. Do not suggest a general search procedure before children need one.')
add('<b>Notice.</b> The top case proves stability need not be unique. The bottom case shows that the same two drawn pairings can have a different answer after preferences change. For a child who already understands the rule these opening tasks may be short; move to a fresh conceptual question rather than repeating filler.')
page()
#4
heading('K-1 / Problems 3 and 4')
sub('Problem 3 / Change exactly one strip, then reset')
add('Both drawn pairings are AX / BY. Test a reversal of one strip <b>on its own</b>, starting from the original printed profile every time. Restore the first strip before testing another. The revised prompt expressly rules out accumulating changes.')
table([['Case','Original strips','Original blocker(s)'],['Top','A: YX; B: YX; X: AB; Y: AB','AY'],['Bottom','A: YX; B: XY; X: BA; Y: AB','AY and BX']],[64,317,147])
table([['Single strip reversed','Top: result','Bottom: result'],['A','Stable','BX still blocks'],['B','AY still blocks','AY still blocks'],['X','AY still blocks','AY still blocks'],['Y','Stable','BX still blocks']],[176,176,176])
add('<b>Answer:</b> circle A and Y in the top case. Cross out the bottom pairing: no single-strip reversal works. In the top case, changing either endpoint of the sole blocker removes that blocker and creates no new one. In the bottom case the two blockers use disjoint endpoints, so a change to one strip cannot affect both.')
hint('First name a blocking pair without changing anything. Then ask whose strip could change that pair\'s wish. If a child reports B as a top-case repair, check whether an earlier change to A was accidentally kept.')
sub('Problem 4 / Fill Y so both pairings can stay')
add('<b>Top answer: Y: A > B.</b> Other strips are A: XY; B: YX; X: BA. AX / BY is stable for either Y order because both circles already have first choices. In AY / BX, B would rather have Y; to prevent BY from blocking, Y must prefer its current A to B. This forces the displayed answer. The other potential blocker AX fails because X prefers its current B.')
add('<b>Bottom: impossible; cross out the blank strip.</b> A and B both rank X first, and X ranks B ahead of A. Thus BX already blocks the straight pairing AX / BY, regardless of Y\'s strip. No filling of Y can make both drawn pairings stable.')
hint('Test the already drawn straight pairing before filling the blank. Can a blocking pair that does not contain Y be repaired by changing Y?')
add('<b>Adult check.</b> Do not let a child silently rewrite X or a circle\'s list in Problem 4. That is a different inverse problem. More generally, if both circles rank X first, having both pairings stable would force X to prefer A to B and B to A at once.')
page()
#5
heading('K-1 / Problems 5 and 6')
sub('Problem 5 / Make only the left pairing stable')
add('The left pairing is AX / BY. Two different valid profiles suffice. For example, use the first two rows below. For an adult checking any invented answer, these are <b>all seven</b> valid profiles; read each entry first to last.')
seven=[t for t in D['all_16_two_pair_profiles'] if t['stable']==['AX/BY']]
table([['A','B','X','Y']]+[[t[a] for a in 'ABXY'] for t in seven],[132]*4)
add('<b>Why this list is complete.</b> There are 2 choices on each of 4 strips, so 16 complete profiles. AX / BY is stable exactly when AY is not mutually desired and BX is not mutually desired. AY / BX must fail through AX or BY. Testing these four possible blocking pairs on the 16 profiles gives precisely the seven rows above. This is adult verification; children are asked for two, not all seven.')
hint('Keep one proposed matching visible. Start by making its partners first choices. Then ask what can be changed while that pairing still stays and the other one fails.')
sub('Problem 6 / Make both pairings stable; find every way')
table([['A','B','X','Y'],['XY','YX','BA','AB'],['YX','XY','AB','BA']],[132]*4)
add('These two rows are the complete answer. In each row one pairing gives both circles first choices; the other gives both squares first choices. Every unmatched pair has an endpoint already at its first choice, so both pairings are stable.')
add('<b>Completeness without 16 trials.</b> If the circles both put the same square first, that square would need to prefer A in one matching and B in the other. Impossible. Thus circle first choices must be distinct. The same reasoning shows square first choices must be distinct. If both sides\' first-choice pairings agree, the other pairing is blocked. They must therefore be opposite. There are exactly two opposite arrangements, shown above.')
hint('Could A and B both put X first? Ask what X would need to want in each of the two pairings. Only after children resolve that case, ask the corresponding question about X and Y.')
add('<b>Stop or extend.</b> Inventing preferences is harder than recognizing a blocker. Offer these pages only if the child is enjoying the inverse problem; two-sided reasoning is the achievement, not completing six problems.')
page()
#6
heading('Grades 2-3 / Problems 1 and 2')
sub('Problem 1 / Keep or challenge the two drawn pairings')
add('<b>Top:</b> only AX / BY stays; join A to X on AY / BX to mark its blocker. The exact strips are A: XY; B: XY; X: AB; Y: AB. <b>Bottom:</b> both stay, so neither receives a challenge line. Strips are A: XY; B: YX; X: BA; Y: AB. See the complete two-pair reasoning on guide page 3.')
hint('Ask for the second preference check before accepting a blocking-pair claim. One letter wanting a new partner does not settle the question.')
sub('Problem 2 / Find every stable three-pair matching')
profiles('unique3')
add('<b>Only AY / BZ / CX stays.</b> Here is a full audit. One witness is enough to reject a candidate; the checker records all blockers.')
blockers_table('unique3')
diagram(['AY/BZ/CX'],left='ABC',right='XYZ',titles=['Unique stable pairing'])
add('<b>Why the survivor is stable.</b> A prefers X to Y, but X prefers current C to A. B prefers X to Z, but X prefers current C to B. C prefers Y to X, but Y prefers current A to C. Those are all the desires for improvement, and none is mutual.')
hint('If completeness becomes the obstacle, keep A-X fixed and try both choices for B, then do the same with A-Y and A-Z. This organizes six possibilities without guessing that a second answer must exist.')
page()
#7
heading('Grades 2-3 / Problem 3')
add('Find all stable pairings and explain completeness. The six blank diagrams allow every candidate to be tested, but children may discover a shorter argument.')
profiles('three3')
blockers_table('three3')
diagram(['AY/BX/CZ','AZ/BX/CY','AZ/BY/CX'],left='ABC',right='XYZ',titles=['AY / BX / CZ','AZ / BX / CY','AZ / BY / CX'])
add('<b>Exact answer: three stable pairings.</b> AY / BX / CZ gives every square its first choice. AZ / BY / CX gives every circle its first choice. Either fact alone prevents a blocker. In the middle solution AZ / BX / CY: A has its first choice; B wants Y, but Y prefers current C; C wants X, but X prefers current B. Hence that solution also has no blocker.')
add('<b>Completeness:</b> A has three possible partners; once chosen, B has two and C has one. The table accounts for all 3 x 2 = 6 candidates. The unstable rows each have a specific mutually improving pair. Crossing lines or similarity between pictures is not a reason to discard a candidate.')
hint('If children find the two first-choice extremes, ask them to challenge one of the remaining four candidates rather than telling them that a third solution exists.')
sub('Extension held in reserve')
add('Ask whether the middle stable pairing gives either entire side first choices. It does not. Stability can hold without either side being universally delighted. Compare A, B, C between the three stable answers: their preference orders all move in the same direction here. This observed pattern is an entry to proposer optimality, not a proof of the general theorem.')
page()
#8
heading('Grades 2-3 / Problem 4')
add('Find all stable four-pair matchings and ask whether all eight letters can get first choices.')
profiles('four4')
diagram(['AW/BX/CY/DZ','AW/BX/CZ/DY'],left='ABCD',right='WXYZ',titles=['AW / BX / CY / DZ','AW / BX / CZ / DY'],height=125)
diagram(['AX/BW/CY/DZ','AX/BW/CZ/DY'],left='ABCD',right='WXYZ',titles=['AX / BW / CY / DZ','AX / BW / CZ / DY'],height=125)
add('<b>Exactly these four.</b> The preferences split into two blocks: {A,B} with {W,X}, and {C,D} with {Y,Z}. Everyone ranks both members of their own opposite block ahead of both outsiders. If a matching crosses blocks, some circle and some square in the same block must each be matched outside it. They prefer one another to their outside partners, so they block.')
add('Thus a stable matching stays inside both blocks. Each two-pair block has the opposing-first-choices pattern and two stable pairings. Choose either answer in the first block and either in the second: 2 x 2 = 4. Between-block pairs cannot block because both participants prefer their present within-block partner. This proves existence and completeness without auditing 24 diagrams.')
add('<b>All eight first choices? No.</b> A wants W, while W wants B. If A receives its first choice W, W does not receive its first choice. Already these two lists rule out the demand. All four circles can get first choices in AW / BX / CY / DZ, but then the squares do not.')
hint('If 24 trials feels unwieldy, ask which two squares A and B place ahead of both others, and whether W and X show a related pattern. Leave the conclusion to the children.')
page()
#9
heading('Grades 2-3 / Problem 5')
add('Invent complete three-choice strips with exactly two stable pairings. There are many correct answers; the following is one fully checked construction.')
profiles('construct2')
diagram(['AX/BY/CZ','AY/BX/CZ'],left='ABC',right='XYZ',titles=['AX / BY / CZ','AY / BX / CZ'])
add('<b>Why exactly two.</b> C and Z rank each other first, so every stable pairing must include CZ; if separated, CZ blocks. With CZ fixed, A/B and X/Y form the two-stable two-pair market. Both remaining pairings are stable. No unmatched pair involving C or Z blocks because each already has its first choice.')
blockers_table('construct2')
add('The table verifies every other pairing fails; its listed witness need not be the only blocker. In every rejected row CZ is also a blocking pair. If children invent another profile, accept it only after checking all six candidates or an equally complete structural argument.')
hint('First make the two-pair example with two stable answers. What can C and Z rank first so they are forced to stay together? Put the new labels in all the old lists too; lists must remain complete.')
sub('A concrete proof invitation')
add('Keep C and Z connected with a removable link. Ask children to try breaking it without creating a blocker. Then cover those two tokens and identify the familiar smaller problem. The physical reduction is a proof, not merely another successful trial.')
page()
#10
heading('Grades 4-5 / Problems 1 and 2')
sub('Problem 1 / Contrast two solutions with one')
add('<b>Top two-pair market:</b> AX / BY and AY / BX, both stable. Every circle gets its first choice in the first answer; every square in the second. <b>Bottom three-pair market:</b> only AY / BZ / CX. The complete six-candidate audit and the direct stability check are on guide page 6; the printed lists are identical. Three blank trial boards do not assert three solutions.')
hint('Ask for a rejecting pair on a discarded matching and then ask how all possible pairings are covered. Do not use the algorithm as a substitute for the small search unless the group asks for one.')
sub('Problem 2 / Run deferred acceptance from both sides')
profiles('older4')
add('Read the printed rules literally: only a free asker acts; it approaches its highest untried choice; the receiver holds the better of the new and current asker, releasing the other. Every hold is tentative. Mark each asked edge once. A rejected asker returns to the free pool; do not erase its proposal history.')
diagram(['AW/BY/CZ/DX','AZ/BY/CW/DX'],left='ABCD',right='WXYZ',titles=['Circles ask: 8 requests','Squares ask: 7 requests'])
add('<b>Answer:</b> circles asking yield AW / BY / CZ / DX. Squares asking yield AZ / BY / CW / DX. <b>Yes, changing the asking side changes the final pairing:</b> A and C exchange W and Z; B stays with Y and D with X. Both results are stable. The exact legal request logs are on the next page.')
add('These are the only stable matchings for this profile (all 24 candidates checked). The printed task asks for the two runs and their comparison, not for this additional enumeration. Any legal order of free askers yields the same result for a fixed proposing side; the general reason is the optional theorem on guide page 16.')
page()
#11
heading('Grades 4-5 / Problem 2 request logs')
add('These are legal sample schedules, not the only allowable request order. In each row, the receiver named in the request is the one whose hold is updated or retained. The tables contain every request, including immediate rejections.')
table([['Step','Circles ask','Receiver keeps','Released or rejected'],['1','A to X','A','None'],['2','B to X','B','A'],['3','A to W','A','None'],['4','C to X','B','C'],['5','C to Y','C','None'],['6','D to X','D','B'],['7','B to Y','B','C'],['8','C to Z','C','None']],[48,160,150,170])
table([['Step','Squares ask','Receiver keeps','Released or rejected'],['1','W to B','W','None'],['2','X to D','X','None'],['3','Y to B','Y','W'],['4','W to C','W','None'],['5','Z to B','Y','Z'],['6','Z to D','X','Z'],['7','Z to A','Z','None']],[48,160,150,170])
add('<b>Direct stability check, circles ask.</b> A wants X, but X holds D. B wants X, but X prefers D. C wants X or Y, but those receivers prefer D and B respectively. D has its first choice. No desired switch is mutual.')
add('<b>Direct stability check, squares ask.</b> A wants X or W, but X prefers D and W prefers C. B wants X, but X prefers D. C wants X, Y, or Z, but they prefer their current D, B, or A. D has its first choice. Hence no blocker.')
hint('If a later request is automatically rejected, ask the receiver to read its own strip. If a released token asks the same receiver again, point to the already-asked marker. The recording boxes suit short letter pairs, not sentences.')
add('<b>Verified schedule independence for this instance.</b> The independent checker branches over every possible choice of a free asker. Every circle-asking terminal run uses 8 requests; every square-asking terminal run uses 7. This instance-specific count is not a claim that all markets have fixed request counts under every scheduling variant.','SmallX')
page()
#12
heading('Grades 4-5 / Problem 3')
add('Change the rule so receivers keep their <b>first</b> asker forever. Produce one complete profile and one legal asking order whose terminal pairing has a blocker.')
profiles('keep_first')
table([['Step','Request under the changed rule','What happens'],['1','A to X','X keeps A.'],['2','B to X','X rejects B solely because A arrived first.'],['3','B to Y','Y keeps B.'],['4','C to Z','Z keeps C. All askers are now held.']],[48,222,258])
diagram(['AX/BY/CZ'],left='ABC',right='XYZ',titles=['Final AX / BY / CZ; dashed BX blocks'],blocks=['BX'])
add('<b>Blocking pair BX:</b> B ranks X ahead of current Y, and X ranks B ahead of current A. Thus the changed rule ends in an unstable pairing. C and Z rank each other first, so the third pair is an innocuous complete addition. All lists still contain all opposite-side labels exactly once.')
add('<b>Why the ordinary rule avoids this failure.</b> On request 2, X would replace A with B. Then A could ask Y and be held. With CZ held too, the result AY / BX / CZ is stable. The important difference is allowing a receiver to improve its hold; merely pairing everyone does not prove stability.')
hint('Arrange for two askers to want the same receiver and let the receiver prefer the one who arrives second. Then decide which rule forces the receiver to make the wrong choice.')
add('<b>Assess the counterexample.</b> A list by itself is not enough: the answer must include an allowed request sequence and a pair who mutually prefer switching in its actual final state. One bad sequence disproves a universal guarantee. Children do not need to show every sequence fails.')
page()
#13
heading('Grades 4-5 / Problem 4')
add('Give a bound on requests and prove the rules finish with everyone paired. Then extend the argument from four per side to ten.')
sub('Exact expected answer: 16 requests; 100 with ten per side')
add('For four askers and four receivers, there are 4 x 4 = 16 distinct asker-receiver requests. No asker repeats a request, so 16 cannot be exceeded. For ten per side, the same reasoning gives 10 x 10 = 100. These are valid upper bounds; neither is asserted to be the smallest possible upper bound.')
table([['Four askers','Receiver W','Receiver X','Receiver Y','Receiver Z'],['A','AW','AX','AY','AZ'],['B','BW','BX','BY','BZ'],['C','CW','CX','CY','CZ'],['D','DW','DX','DY','DZ']],[112,104,104,104,104])
add('One physical proposal marker in a cell records a used request. Every move fills a previously unused cell. This makes the finite bound concrete without assuming children can manipulate n-squared notation.')
sub('The missing step a finite-count argument must include')
add('After a receiver first holds someone, it never becomes empty: a change is an exchange, not a vacancy. Also, an asker is held by at most one receiver, because only free askers make requests. Suppose a free asker had already asked every receiver. Then every receiver would have received a request and would be holding an asker now. Four distinct holds account for all four askers, so no asker can be free. This is a contradiction.')
add('Therefore, whenever some asker is free, it still has an untried receiver. The rules can make another legal request. They cannot do so forever because no request repeats. They must stop with every asker held, and hence with every receiver holding exactly one asker. This proves a perfect pairing, not merely an end to the procedure.')
hint('First count the available request markers. If the child says "therefore it finishes," ask whether an asker could be free with every marker used. What would that tell you about all receivers?')
sub('For any equal size')
add('With n labels on each side there are n x n possible requests. The same nonempty-hold and distinct-asker arguments work for every n. No ordering of the free askers is needed, and no fairness assumption about whose turn comes next is needed in a finite execution: each actual request consumes a new edge.')
page()
#14
heading('Grades 4-5 / Problem 5')
add('Can two letters in different pairs both prefer one another after the ordinary asking rules finish? <b>No.</b> This page gives the universal proof, not a conclusion drawn from sample runs.')
sub('Two facts to uncover with the physical cards')
table([['Askers move down their own lists','Receivers improve their holds'],['An asker tries choices from first to last and never repeats. Before reaching its eventual partner, it has asked every receiver it ranks higher.','A receiver replaces its hold only with someone it prefers. Once it has rejected an asker, every later hold is preferred to that rejected asker.']],[264,264])
sub('Proof by considering an alleged blocking pair')
add('Call the asker p and the receiver r. Suppose p prefers r to its final partner. Because requests follow p\'s ranking, p must already have asked r before asking its final partner. Since they are not together at the end, r either rejected p immediately or held p and released it later.')
add('At that rejection, r kept another asker q whom it preferred to p. Afterward, r\'s hold could only improve. Its final partner is therefore preferred to p as well. So r does <b>not</b> prefer p to its final partner. The two preferences required for a blocker cannot both hold. This argument applies to every unmatched p-r pair, proving stability.')
table([['Possible history at r','What r\'s preference tells us'],['p asks; r already holds q and rejects p.','q is ahead of p in r\'s strip.'],['Or: r holds p; q arrives and p is released.','Again q is ahead of p.'],['Later r keeps q or exchanges it for better holds.','The final hold is still ahead of p.']],[264,264])
hint('Choose an asker who claims to want a better final partner. "Did it ever ask that receiver? What happened there? Could that receiver\'s hold get worse afterward?" Let the child supply the link between the two lists.')
sub('What counts as a complete explanation')
add('Accept a spoken argument with cards, a chronological drawing, or a written proof. It must connect <b>the asker\'s earlier request</b> to <b>the receiver\'s final preference</b>. "We tried lots of lists" and "receivers get better" alone are incomplete. Combining this result with Problem 4 proves that a stable perfect matching exists for every strict, complete, equal-sized two-sided instance.')
add('<b>Boundary of the guarantee.</b> Do not carry this proof unchanged into ties, omitted choices, unequal sides, multiple-place capacities, or one-set roommate matching. Those are different models. The cards represent artificial objects; the exercise makes no claim about measuring real people\'s happiness or fairness.')
page()
#15
heading('Grades 4-5 / Problem 6')
add('Make a stable three-pair matching with as many last-choice recipients as possible. <b>The maximum is three of the six letters.</b> This does not require proposer optimality.')
profiles('last3')
diagram(['AX/BY/CZ'],left='ABC',right='XYZ',titles=['AX / BY / CZ: circles first, squares last'])
add('<b>Construction:</b> choose AX / BY / CZ. Every circle receives its first choice, so no circle prefers any alternative and there can be no blocker. X receives A, its last choice; Y receives B, its last; Z receives C, its last. Thus three last-choice recipients are possible.')
sub('Why four cannot occur')
add('If four of the six letters received last choices, last-choice recipients would occur on both sides because each side has only three letters. Among those recipients, choose a circle and a square who are <b>not paired to one another</b>. Such a pair must exist: if there is just one last-choice circle, there are three last-choice squares and it is paired with at most one of them; if there are two or more on each side, any chosen circle has at least one nonpartner among those squares. The case with one square is symmetric.')
add('Each of the selected nonpartners prefers <b>every</b> other opposite-side label to its current last-choice partner. In particular, each prefers the other. They form a blocking pair, contradicting stability. The same reasoning rules out five or six: any set of at least four contains such opposite-side nonpartners. Therefore the exact maximum is three.')
hint('Try giving a whole side its first choices. For the upper bound, place a marker on each last-choice recipient and ask whether a marked circle and a marked square in different pairs could coexist.')
sub('Independent numerical check, not the proof')
add('All 46,656 complete strict three-pair preference profiles and their six candidate matchings were checked independently: 279,936 candidates in total, 60,324 stable outcomes counted over the profiles, and a largest last-choice count of 3. The contradiction above explains why; the finite audit only cross-checks it.')
page()
#16
heading('Optional depth and responsive facilitation')
sub('Extension A / Does the free-asker order matter?')
add('It does not change the final pairing for a fixed proposing side in this model. This is optional, quantifier-heavy work. Use it only when children can distinguish a pair in <i>some</i> stable matching from a pair in the current tentative process.')
add('<b>First-rejection proof.</b> Assume there is a first rejection of a pair that belongs to at least one stable matching. Call the rejected asker p, the receiver r, and the kept asker q; choose a stable matching S containing p-r. Since r chose q, r prefers q to p. If q preferred its S-partner to r, q would have asked that partner earlier and been rejected before reaching r. That would be an earlier rejection of a pair belonging to a stable matching, contrary to the choice of the first rejection. Also q\'s S-partner cannot be r, since S pairs r with p. Hence q prefers r to its S-partner. Then q-r blocks S, a contradiction.')
add('Thus no pair occurring in any stable matching is ever rejected. Every receiver ahead of an asker\'s final partner has rejected it. None could be its partner in a stable matching. Therefore every asker obtains its most-preferred partner among <b>all stable matchings</b>. Strict preferences make each such best partner unique, so changing the order of free askers cannot change the outcome. Reversing the proposing side can change it, as Problem 2 shows.')
hint('Return to the two-stable two-pair example first. Ask what "best possible while still stable" means before attempting the general proof. Do not relabel this as best for both sides or maximum total satisfaction.')
sub('Extension B / More last choices')
add('For n >= 3, the maximum possible number of last-choice recipients is n. Give all askers distinct first choices and place each chosen asker last on its receiver\'s list; that supplies n. If more than n are last, both sides contain last-choice recipients and an opposite-side nonpartner pair exists, which blocks. For n = 2 the maximum is also 2 (one first-choice side construction); for n = 1 both labels simultaneously have their first and last choice, so the answer is 2. Keep this boundary case if generalizing.')
sub('Observe before revising')
add('Record the actual date, participants and packet version; problems offered and attempted; whether children checked both preferences without rescue; which representation helped; any cumulative-strip mistake; whether request markers prevented repeated requests; and what children wanted to continue. Separate observations from guesses about why they occurred. Record this slot as used only after an actual meeting, and keep its draft/unpiloted status until then.')
add('<b>Misconceptions worth pausing for:</b> "everybody gets a first choice"; a unilateral wish counted as a blocker; crossing lines judged illegal; preferences changed halfway through a run; or temporary holds treated as permanent. Fix the concrete rule with one example, then return ownership of the investigation to the children.','SmallX')
page()
#17
heading('Sources, fidelity, and verification')
sub('Mathematical references verified on 2026-10-03')
add('<b>Rafael Pass and Joseph Y. Halpern, <i>A Course in Networks and Markets: Game-theoretic Models and Reasoning</i>, Chapter 14, Sections 14.1-14.3.</b> The online chapter was opened and read for the two-sided definition, deferred-acceptance existence/correctness argument, and proposer optimality. This is the directly read proof reference.<br/><link href="https://www.cs.cornell.edu/~rafael/networks-html/chapter14.html" color="#146878">cs.cornell.edu/~rafael/networks-html/chapter14.html</link>')
add('<b>David Gale and Lloyd Shapley, "College Admissions and the Stability of Marriage," <i>American Mathematical Monthly</i> 69 (1962), 9-15.</b> Historical origin of the stable-matching method. The university-hosted seven-page scan was opened; it yielded no extracted text in this workflow. It is included as a historical reference, not claimed as the directly text-verified proof source.<br/><link href="https://iqua.ece.toronto.edu/baochun/ece1771f/papers/Gale-Shapley-1962.pdf" color="#146878">University-hosted Gale-Shapley scan</link>')
sub('Teaching reference and local evidence')
add('<b>Natasha Rozhkovskaya, <i>Math Circles for Elementary School Students</i>, "Introduction: Berkeley 2009."</b> The local EPUB introduction describes adult support and active parent involvement in the elementary circle. It supports the adult-at-table arrangement; it does not validate this stable-matching packet or establish kindergarten readiness. The introduction was directly read from the downloaded MSRI collection.')
add('Local project guidance and the September 2026 classroom review emphasize concrete handling, brief shared launches, prerequisite-based routing, and preserving time for one idea. The particular timing menu, held hints, and suggested card arrangement here are design proposals. No classroom results from this Week 27 revision are claimed.')
sub('Fidelity to the final student packets')
add('This guide keys W27-K-v3 (7 pages, Problems 1-6), W27-23-v3 (6 pages, Problems 1-5), and W27-45-v2 (6 pages, Problems 1-6). It preserves all printed profiles and tasks. K-1 Problem 3 tests one reversed strip at a time; the older Problem 2 explicitly compares proposing sides. Compact older diagrams record work done with separately supplied large cards. The upper packet retains its hold/release example. K-1 and middle page 1 check P-U with current PV/QU: yes/yes blocks; yes/no rejects only that candidate. No conclusion about the whole pairing follows from the failed check.')
sub('Checks packaged with the editable source')
add('The independent Python checker transcribes the printed preference profiles instead of importing the student solution code. It enumerates all candidates for every supplied market, all 16 two-pair profiles, all 46,656 three-pair profiles, and every free-asker schedule for the older four-pair example. It verifies both constructions and impossibility bounds. The proof explanations in this guide remain necessary; enumeration is not a universal proof.')
add('The portable source folder contains the ReportLab builder, independent checker, JSON results, rebuild instructions, source manifest, student-file hashes, and page/visual QA record. Rendering is checked for every guide page. The materials, pacing, and learning effectiveness remain unpiloted. Suitable future revisions should be driven by observed use, not the number of pages completed.')

if __name__=='__main__':
 doc=SimpleDocTemplate(str(OUT),pagesize=letter,rightMargin=42,leftMargin=42,topMargin=38,bottomMargin=43,title='Week 27 - Stable pairings - Facilitator guide',author='Bellingham Math Circle')
 doc.build(S,onFirstPage=footer,onLaterPages=footer,canvasmaker=lambda *a,**kw: canvas.Canvas(*a,**(kw|{'initialFontName':'Guide'})))
 print(OUT)
