from pathlib import Path
base=Path('plans/encore-01-05')
common='''
Return-visit scope and format

This is NEW companion work, not replacement pages. Exactly three substantial investigations are wanted, each with an elementary concrete entry and an optional deeper question in the adult guide. Use one shared three-page packet, `draft/return-visit.pdf`, with one numbered Problem per page (Problems 1–3 consecutively). Header: Week N / TOPIC / Grades 2–5; if genuine younger entry exists note that only in the adult guide. No compulsory three-band files: the delegation specifically overrides the harness’s three-file requirement. Physical mats or cutouts may add pages when essential. Leave real room for constructions and a light recoverable record. Choose the actual tasks; do not turn the mathematical kernels into a printed algorithm. Do not print solutions or optional adult hints.

Existing material was inventoried from ALL current band PDFs and extras. The novelty constraints below are mandatory. These pages are explicitly authorized week-local review drafts; they remain unpiloted. Read the current AGENTS.md before drafting. Keep all stage files as generated plus this scope in the outline; do only this stage.
'''
materials={1:'Per pair: 12 small green equilateral triangles and 12 small blue rhombi, one-inch edges; other blocks set aside. A 1-inch scale bar if drawing a working mat; favor free tabletop building and compact recording sketches, not fit-sensitive printed boards. Paper/pencil and tracing paper optional. Green corners are 60 degrees; blue corners are 60 or 120 degrees. Rotations of a finished design carry its internal seams with it.',2:'Per pair: 6 reversible counters (clearly different faces), paper numbered lamp boards with counter positions at least 20 mm wide; card switch strips may physically span the selected lamps. A partner changes ALL specified counters. Blank paper, pencil, folder to hide wiring in one investigation. No real electrics. ON/OFF state is externalized in counters.',3:'Per pair: 6 numbered cards or blocks, ordered home mat with slots at least 25 mm wide; pencil, empty arrow machines with one outgoing and one incoming arrow per slot. Use no larger deck. Cards remain face-up. Adjacent exchanges, rotations and reversals must be physically demonstrated separately. Recording a move word plus final order suffices.',4:'Per pair: two differently colored counters, numbered rings of 8–12 positions at least 20 mm wide (one wide ring/page when working on it), 12 red and 12 blue counters, pencil and paper. Counters jump clockwise unless stated. Time advances in synchronized turns. Pattern equality includes the colors; no reflection equivalence unless explicitly asked. Offer drawings and hand turns instead of fractions or modular notation.',5:'Per pair: 40 snap cubes to build a 4-by-4 city or 18 to build a 3-by-3 city, 25-mm minimum grid squares, pencil. All rows and columns have exactly one of each height. Touching means sharing a side, not a corner. A city may be sketched using a single height number per square after building. No roof walk rule relies on line-of-sight.'}
kernels={
1:'''1. Perimeter from joining pieces: for edge-to-edge connected arrangements of t small triangles and r small rhombi, P = 3t + 4r - 2s in unit edges, where s counts internal full unit sides shared by two pieces. Joining along one side removes two perimeter edges. Holes contribute their boundary; touching at a point does not join pieces. For fixed inventory, different adjacency/contact patterns change P, while area stays t+2r small triangles. Explore contrasting compact vs stretched arrangements and seek extremal boundaries, without assuming the formula gives realizability.

2. Corner packing: angles at an interior meeting point total 360 degrees. A green corner or acute blue corner consumes one 60-degree sector; an obtuse blue corner consumes two. Thus g+a+2o=6 is necessary, and fans of unit-edge corners can realize the locally allowed sector patterns; a full tiled region imposes additional global restrictions. Concrete fitting should precede numbers/degrees. Discover which counts of pieces can close a gap around a marked point and which mixtures cannot.

3. Rotational symmetry of a fixed tiled hexagon: a rotation is a symmetry only if every piece and seam lands on a corresponding piece/seam. Six green triangles meeting at the center admit 60-degree rotations; three rhombi meeting there admit 120-degree rotations and not 60-degree rotations. A finite pattern's symmetry rotations form a subgroup of the six hexagon turns, so possible orders divide 6 (1,2,3,6). Children create and test mosaics, including asymmetry and reflection distinctions; no need to enumerate every tiling.''',
2:'''1. Hidden wiring identification: a switch toggles a fixed subset of lamps; seeing both before and after identifies that subset. For three independent unknown switches on three lamps, three separate one-switch experiments suffice and fewer experiments cannot distinguish all 2^9 possible panels (each observed three-lamp result supplies at most three binary facts). A partner hides three subset cards and operates honestly. The first discovery is wiring from observed changes; the deeper question is minimal guaranteed trials, not base solvability.

2. Three-lamp moves on a ring: switch i toggles lamps i,i+1,i+2 cyclically. For n>=3, null press choices satisfy x_i+x_(i-1)+x_(i-2)=0 modulo 2, hence repeat with period 3. If n is not divisible by 3 only the zero choice changes nothing, and every target has a unique subset of presses. If 3 divides n there are four do-nothing choices and only 2^(n-2) reachable targets; the three residue-class lamp parities must agree from all OFF. Use n=4,5,6 for concrete work. Keep a visible press marker rather than mental state.

3. Lamp transport: a NEW switch exchanges the two endpoint counters rather than toggling them. On a connected graph exactly the ON-count is invariant; every picture with the same count is reachable. On a line, list ON positions a_1<...<a_k and target b_1<...<b_k: minimum adjacent exchanges = sum |a_i-b_i|, because ON particles cannot cross one another and each exchange moves one ON one step. Compare line versus cycle shortcut experiments; give the exact formula only to adults.''',
3:'''1. Adjacent sorting: for distinct ordered cards, an inversion is an out-of-order pair. One adjacent swap changes inversion count by exactly one; swapping adjacent inverted pairs sorts, so the minimum is the inversion count. Use small concrete scrambled rows and child-chosen hard rows; formal definition belongs to guide unless child task needs it.

2. Restricted rearrangements: a move rotates a row one place (last card to first) or reverses its entire order. For n distinct cards these produce exactly the 2n cyclic orders and their reverses for n>=3, preserving which unordered pairs are neighbors when the row is wrapped into a ring. This excludes most permutations. For n=4 reachable count8 of24, n=5 count10 of120. Kids physically compare reachable/unreachable orders; use a circular layout bridge before invariance discussion.

3. Machine square roots: can one fixed permutation run twice produce a specified target permutation? An odd cycle has a square root on the same cards (step (length+1)/2); squaring a 2k-cycle splits into two k-cycles. A square root exists iff the number of cycles of each even length is even. Thus one swap alone impossible, two disjoint swaps possible via a four-cycle; a three-cycle has a root. Offer target machines with 3,4,6 slots for concrete construction; generalized criterion is adult extension, not an undergraduate prerequisite.''',
4:'''1. Two moving counters meet: on an n-position ring, counters beginning at a,b and moving u,v each turn meet at t iff (u-v)t=b-a modulo n. Meetings exist iff gcd(n,u-v) divides b-a. If they start together, the first positive meeting is n/gcd(n,u-v). Explicitly both move before checking; a crossing between dots does not count. Varied examples show both delayed and impossible meetings.

2. Two permitted hops: with choice of clockwise hops a or b each turn, reachable positions from 0 are exactly multiples of gcd(n,a,b), because on a finite ring backwards steps can be replaced by enough forwards steps. Allowing two noncoprime hops may reach all dots together: n=12,a=4,b=3. Shortest routes are a different question, found by BFS on directed choices. Compare to base fixed-hop orbits; child-owned route search comes first.

3. Coloring necklaces: binary colorings around a ring may have smaller repeat blocks. A coloring with rotational period d on n beads has d dividing n and n/d symmetry rotations. For n=6 with exactly three red/three blue beads there are four classes under rotation only; under rotation AND reflection there are three classes (two rotation classes are mirror partners). Explicit rotation-equivalence conventions essential; all20 labeled patterns give 4 rotation classes. Concrete necklaces and comparing hand rotations ground the classification.''',
5:'''1. Local city trades: in a Latin city, an alternating 2-by-2 rectangle a,b / b,a can swap a and b at all four corners without breaking rows/columns; the rectangle need not consist of adjacent squares. A 3-by-3 Latin square has no such two-height trade; order4 cities have either four or twelve such trades (four in the cyclic-type family, twelve in the Klein-type family); smaller embedded rectangles need not admit a trade. Concrete attempts should reveal the condition rather than print it. A changed city may change visibility clues, so this is a repair rule, not a claim of clue preservation.

2. Diagonal city conditions: require each main diagonal as well as rows/columns to contain one of every height. None of the12 order3 Latin squares meets BOTH diagonal conditions; an order4 example exists, and of576 labeled order4 Latin squares48 satisfy both. A main diagonal is corner-to-opposite-corner, explicitly highlighted. A city can satisfy one diagonal without the other. Enumeration of3 plus a constructive4 example is elementary; do not require listing576.

3. Climbing roof routes: from a square move to a side-neighbor of strictly larger height. Every route terminates because height strictly increases. A peak is a square with no higher side-neighbor; even a non-tallest tower can be a peak. In Latin cities rows/columns unique, all tallest towers are peaks, but others can also be. For3 and4 enumerate possible peak counts and find contrasting city designs; attempt to make every start reach a tallest tower is equivalent to having no lower peaks. This is an increasing-path/local-versus-global question, different from base skyline visibility.'''}
novel={1:'Do not duplicate base triangle packing, equal-up/down matching, purple-vs-blue packing, six-state rhombus flip graph or ribbons; existing extensions have matching, word distances, shortest-route counts and random walks; existing encore has placement games, fewest/most pieces, trapezoid imbalance, cube stacks and trapezoid flips. NEW directions: boundary length, angle closure, symmetry of entire seam pattern. Prior-year Pattern Block Exercises p.2 classifies leftover triangles by symmetry; the new direction designs whole-mosaic rotational symmetries instead.',2:'Do not repeat base target reachability, per-component parity, bridges, all line subsets, shortest solutions, hardest rings, solution-count cycle spaces; existing bonus adds do-nothing sets, bridge detective, solo button and weighted cheapest route. NEW directions: unknown circuit identification, three-counter ring switches, exchanging existing ON states instead of toggling.',3:'Do not repeat base return times/orders, all machines on n slots, inverse machines, composition noncommutativity, commuting examples, maximum return time or perfect shuffles. NEW directions: shortest adjacent sorting, restricted rotate/reverse reachability, identical-machine two-turn reconstruction.',4:'Do not repeat base fixed hop stars/gcd-piece counts, inverse hop, additive cipher wheels, two cipher settings, prime ring sizes, erased-star reconstruction or multiplication webs. NEW directions: meetings of different-speed counters, routes with a choice of two hops, classification of colored necklaces with rotational/reflection conventions.',5:'Do not repeat base all tower row orders, visibility clues, 3/4-by-4 clue puzzles, minimal unique clues, all3-by-3 cities, clue totals, row record counts or equal sixteen-clue cities. NEW directions: local Latin trades, extra diagonal constraints, strict climbing routes and lower peaks.'}
for w in range(1,6):
 topic={1:'Pattern-block return visits',2:'Lamp return visits',3:'Shuffle-machine return visits',4:'Stars-and-wheels return visits',5:'Tower-city return visits'}[w]
 text=f'Week {w}: {topic}\n\nMathematical kernels\n\n{kernels[w]}\n\nSources: elementary geometry, graph dynamics, permutations, modular arithmetic and Latin squares respectively; kernels independently derived here, not adapted problem statements. Pedagogy: Math Circle by the Bay, Preface printed pp. viii–x (PDF pp.9–11), supports themes that deepen over years and variable pace; the three-investigation format is our design inference.\n\nSuggested emphasis by level: K–1: genuine concrete construction/turn-taking entries only; Grades 2–3: manipulate, compare, find examples; Grades 4–5: organize complete small cases, establish bounds/impossibility, extend conjectures. One Grades 2–5 packet with adult-read concrete entry where suitable; do not manufacture a separate young-child problem.\n\nMaterials\n\n{materials[w]}\n\nNovelty vs existing\n\n{novel[w]}\n'+common.replace('Week N','Week '+str(w)).replace('TOPIC',topic)
 (base/f'week-{w:02d}-outline.md').write_text(text)
