from pathlib import Path
import json
root=Path(__file__).resolve().parents[2]
statusfile=root/'plans/encore-01-05/delivery-checks.json'
statuses=json.loads(statusfile.read_text()) if statusfile.exists() else {}
rows={1:[('Boundary at fixed inventory','2–5; K–1 concrete comparison with adult','Changes contact structure/edge boundary, not packing or piece count'),('Corner closure','K–5 concrete; 2–5 organize mixtures','Acute/obtuse corners around a point, not fixed-board filling'),('Whole-seam rotational symmetry','K–5 concrete; 2–5 classification','Creates symmetric/asymmetric mosaics, unlike prior leftover-position symmetry')],2:[('Hidden wiring detective','2–5; supported K–1 observation entry','Infers unknown switch subsets from experiments'),('Three-lamp ring switches','2–5; K–1 with operator/record help','Changes switch rule; period-three null patterns replace pair parity'),('Lamp transport by exchanges','K–5 concrete; 2–5 optimal routes','Preserves exact ON-count; particles move instead of toggling')],3:[('Shortest adjacent sorting','2–5; supported K–1 ordering entry','Inversion lower bound, not machine return time'),('Rotate/reverse reachability','2–5; K–1 physical trial entry','Restricted move set and cyclic-neighbor invariant'),('Identical-machine two-turn reconstruction','4–5; 2–3 ready for arrow trials','Square roots rather than inverse/composition')],4:[('Moving counters meet','2–5; supported concrete counting','Relative speeds/offsets instead of one fixed hop'),('Choice of two hops','2–5; K–1 trial routes with adult','Generated reachable set rather than single-hop orbit'),('Colored necklace classes','K–5 concrete; 2–5 complete classification','Rotation/reflection equivalence of colorings')],5:[('Local city repair trades','2–5; supported K–1 tower comparison','Generalizes base upper P9’s one four-cell equal-clue swap into a repair catalog, 3-height obstruction and minimum changes; city B is familiar'),('Diagonal cities','2–5; concrete entries by 3-height city ability','Additional diagonal consistency/impossibility'),('Strict-climbing roof routes','K–5 concrete; 2–5 peak analysis','Local/global height maxima and terminating paths') ]}
lines=['# New return-visit companions, Weeks 1–5','', '**Status:** review drafts, unpiloted; physical rehearsal untested. Base packets, existing Week1 encore/extensions, existing Week2 bonus, guides, combined sets and global indexes were untouched. Each row below is one investigation; contrasting cases within it are not counted as additional investigations.','', '| Week | Investigation | Suitable entries/readiness | New versus base | Companion paths | Checks |','|---|---|---|---|---|---|']
for w,items in rows.items():
 s=statuses.get(str(w),{})
 check=s.get('summary','Outline + independent kernel checks complete; student workflow/delivery pending')
 paths=f'`week-{w:02d}/week-{w:02d}-return-visit.pdf`; `week-{w:02d}/week-{w:02d}-return-visit-facilitator.pdf`; `source/week-{w:02d}-return-visit/`'
 for name,bands,novel in items:lines.append(f'| {w} | {name} | {bands} | {novel} | {paths} | {check} |')
lines+=['','Paths are relative to `lowell-math-circle-year-2/`. Every source directory supplies editable student/adult sources, a portable build script and checks. Its `source/week-NN-return-visit-source.zip` sits beside the directory.','', '## Evidence','', '- Full prior-content inventory: `plans/encore-01-05/inventory-base.md`. All current band/variant student PDFs and existing Week1/2 extra material were opened and fully text-extracted before choosing the new directions.','- Kernel outlines: `plans/encore-01-05/week-NN-outline.md`; workflow stage files: `tmp/worksheet-runs/encore-week-NN-20261004-v1/`. Each writer, critic, math critic and reviser is a fresh per-week agent.','- Independent finite checks: `plans/encore-01-05/verify_kernels.py`, `kernel-checks.json`; geometric enumeration: `verify_triangles.py`, `triangle-checks.json`. All represented final examples receive stage and coordinator checks.','- Source/pedagogy distinctions: `plans/encore-01-05/source-notes.md`.','- Supplementary independent parent outside-repository ZIP rebuilds for Weeks 1–4: `plans/encore-01-17-support/week-NN-outside-rebuild.json` and its reproducible `check-outside-rebuild.py`; all 28 pages match text and 1.5× pixels. Original coordinator extraction locations remain recorded accurately.','- Per-output page, clean-extraction rebuild and comparison evidence: `plans/encore-01-05/delivery-checks.json` as weeks complete. Exact extracted-source/output paths and working directories are recorded, with an explicit flag distinguishing inside- and outside-repository extractions.','', 'No remote upload, publication, commit or push was performed. These are new local review deliverables. The organizer should record actual use, the exact instances tried, observations and next questions before treating a companion as tested.']
(root/'plans/bonus-weeks-01-05.md').write_text('\n'.join(lines)+'\n')
