#!/usr/bin/env python3
"""Generate unit-scale mats and checked best-packing diagrams for grades 2–3."""
import json
from math import sqrt
from pathlib import Path

HERE=Path(__file__).resolve().parent
DATA=json.loads((HERE/'../../../plans/week-01-classroom-middle-checks.json').resolve().read_text())

def point(p): return '({:.9f},{:.9f})'.format(p[0]+p[1]/2,p[1]*sqrt(3)/2)
def path(poly): return '--'.join(point(p) for p in poly)+'--cycle'

out=[r'% Generated by generate-middle-geometry.py from checked lattice packings.',
     r'\newcommand{\MiddleBoard}[2]{\begin{tikzpicture}[x=#2\blockside,y=#2\blockside]\csname MiddleGrid#1\endcsname\end{tikzpicture}}',
     r'\newcommand{\MiddleSolution}[3]{\begin{tikzpicture}[x=#3\blockside,y=#3\blockside]\csname MiddleGrid#1\endcsname\csname MiddlePacking#1#2\endcsname\end{tikzpicture}}']
for name,d in DATA.items():
    cells=d['cells']
    grid=''.join(r'\draw[gridline] '+path(c)+';' for c in cells)
    grid+=r'\draw[outline] '+path(d['polygon'])+';'
    out.append(r'\expandafter\def\csname MiddleGrid'+name+r'\endcsname{'+grid+'}')
    for color,shade in [('blue','black!5'),('purple','black!15')]:
        drawing=''.join(r'\draw[tile,fill='+shade+'] '+path(p)+';' for p in d[color]['placements'])
        drawing+=r'\draw[outline] '+path(d['polygon'])+';'
        out.append(r'\expandafter\def\csname MiddlePacking'+name+color+r'\endcsname{'+drawing+'}')
(HERE/'middle-geometry.tex').write_text('\n'.join(out)+'\n')
print('Generated exact middle mats and blue/purple packing witnesses.')
