"""Editable prose for the adult guide. One entry is one intended page.
Final student problem numbering and square/circle status are authoritative.
"""
PAGES=[]
def page(title,sub='',figs=(),sections=(),table=None):
    PAGES.append(dict(title=title,sub=sub,figs=list(figs),sections=list(sections),table=table))

page('Averaging facilitator guide','Week 20 library slot | Draft and unpiloted | Prepared 3 October 2026',sections=[
('Purpose','Use this adult key with the finalized Averaging packets. Children build arrangements whose circles all equal the average of their neighbors at the same time, then investigate whether a hidden high or low value is possible. The destination is a local-to-global argument, with uniqueness as an optional deeper continuation.'),
('Status and scope','Week 20 is an unscheduled activity-library slot, not a booked meeting. Both the student revision and this separate adult-guide step are unpiloted. This guide has been mathematically checked and visually reviewed; those checks are not evidence of classroom success. Worked examples were added on October 4; numbered tasks and answers are unchanged.'),
('Choose by readiness','K-1: count and compare stacks through 6, recognize 0 as an empty place, and share into two or three equal piles with adult help. Reading is supplied aloud. Finding all arrangements and explaining impossibility are genuine mathematical goals; independent writing is optional.'),
('', 'Grades 2-3: add small collections and divide by 2 or 3, follow which places are joined, and check two conditions together. Multiplication facts help but cubes can replace them. Problems 3-6 ask for reasoning beyond calculation.'),
('', 'Grades 4-5: average up to four neighbors, distinguish an example from an argument for every finite board, and follow a chain of forced equalities. Problem 5 benefits from signed differences and distributivity, so it is optional. Problem 7 needs halves and thirds. Neither algebraic equation solving nor calculus is an entry requirement.'),
('Navigation','Pages 3-4: preparation, launch, and adult mathematical tools. Pages 5-11: K-1 Problems 1-7. Pages 12-17: Grades 2-3 Problems 1-6. Pages 18-24: Grades 4-5 Problems 1-7. Page 25: sources, limits, and use notes. Within each student packet, problem number equals page number.'),
('Keep the key with adults','Solution drawings are small reference diagrams, not stack mats. Squares mean fixed places; circles must average all directly joined places. Hold hints until a child has made a real attempt or asks for help. Offer one hint at a time, then return the work to the child.')])

page('Preparation and the hour','A flexible menu for eleven children and three adults',sections=[
('Prepare in about 15 minutes','Print the student pages single-sided on US Letter at 100%. Full packets for the current 4 / 4 / 3 grouping use 73 sheets, but offer only a few pages at a time. Per table: about 80 counters or connecting cubes, six small stack mats, 12 blank number cards, eight edge strips, blank paper, pencils, and a small whiteboard. Have spare paper for a seventh place on the largest board. Keep 0-4 cards together for K-1 Problem 4. Fraction cards are printed on Grades 4-5 page 7; no cutting is necessary.'),
('Practical setup','Squares and circles must be distinguishable without color. K-1 working nodes are about 3 cm across; use those or enlarged mats for stacks. Older diagrams are writing-size. Build one large board at a time and keep spare cubes beside it. Copy neighbor stacks into a separate sharing area to check an average: do not redistribute the reference stacks. The amounts on the board are independent; their total is not conserved.'),
('Shared launch in 4 minutes','After a few minutes of free handling, show a square with 0 cubes and a square with 6, each joined to one empty circle. Say: "The squares keep their stacks. This circle needs one equal share of the stacks joined to it. How many piles must we make?" Use six spare cubes to make two piles of three, including a pile for the empty neighboring place. Put a separate stack of three on the circle. Ask a child to check it. Show a second circle elsewhere and say: "On a bigger board, every circle has to work at the same time." Stop before giving a solving method.'),
('Suggested timing','0-4 minutes: handle materials. 4-8: shared launch. 8-28: first exploration. 28-31: stand, stretch, or silently point to every neighbor of a drawn circle. 31-51: continue or choose a new question. 51-58: share one arrangement and one reason. 58-60: reset materials. The two work blocks give about forty minutes; shorten the break if children are absorbed.'),
('Table routes','K-1: begin with the one-circle Problem 1, then inverse-build Problem 3 or 4. Return to linked-circle Problem 2 only when children can keep both circle stacks fixed and check them against the same whole board. Problems 5-7 remain further investigations. Grades 2-3: start 1-2, choose 3 or 4, then 5 or 6. Grades 4-5: start 1-2, make 3 the proof destination, then choose 4, 5, 6, or 7. Finishing all pages is not the goal. Move across bands when prerequisites fit.'),
('Adult roles and stopping points','One adult stays mainly at each table, with the parent volunteer at K-1 and the two mathematicians at the other groups. Scribe a child\'s arrangement without supplying it. A useful stopping point is a checked simultaneous filling, a complete small collection, or a convincing impossibility reason. Save unfinished investigations for another library use.')])

page('Adult mathematical tools','Use after concrete attempts; these are held explanations',sections=[
('What a legal board means','The packet uses finite undirected graphs with no loops or repeated edges. A neighbor is a place joined by one line. Every circle has at least one neighbor. Squares are exempt from the averaging condition. For a circle of degree d, d times its value equals the sum of its d neighbors. One frozen arrangement must pass every circle check; successive partly correct states do not count.'),
('Averages and equal gaps','An average cannot exceed its largest entry or fall below its smallest. If all d entries are at most M and one is smaller, their sum is less than dM. Thus an average of M forces every entry to equal M. Also, on a path, 2b = a + c means b - a = c - b. Consecutive gaps are therefore equal. With L edges between fixed endpoints A and B, every gap is (B - A)/L. This derives the path answers and their uniqueness.'),
('Maximum and minimum principle','Work in one connected component with at least one fixed square. If some value exceeds all its square values, choose a greatest value M in that component; it exists because the graph is finite. It occurs at a circle. Every neighbor is at most M, so each must equal M. Choose a path from this circle to a square, stopping at the first square. Repeating the same argument at each intermediate circle forces that square to equal M, contradicting the assumption. For a value below every square, choose a least value and repeat with inequalities reversed. Thus every value lies between the smallest and largest square values in its component.'),
('Uniqueness','Suppose f and g are two legal fillings with the same fixed values. At every place form h = f - g, allowing negative numbers. At a circle, h is the average of its neighbors because subtraction commutes with addition and division by the degree. All squares have difference 0. Applying the maximum and minimum principle to h gives 0 <= h <= 0, so h is identically 0 and f = g. This proves at most one filling. It does not, by itself, prove a filling exists.'),
('Boards without squares','On a finite connected board of circles only, take a greatest value M. Its neighbors must equal M; connectedness spreads M everywhere. Conversely, a constant filling always works. Disconnected circle-only boards can choose a separate constant in each component. There is no fixed boundary bound. Avoid isolated circles: the average of an empty neighbor set is undefined in this activity.'),
('Three guardrails','Equality with a square extreme is allowed; propagation stops when it meets a square. Whole-number restrictions can prevent existence even when a fractional solution exists. Repeatedly adjusting circles is useful experimentation, but neither a finite list of failed attempts nor apparent numerical settling proves impossibility or exact convergence.')])

page('K-1 Problem 1','Student page 1 | Make the four one-circle stacks',figs=['K1.1','K1.2','K1.3','K1.4'],sections=[
('Exact answers','In reading order, the circles contain 1, 3, 2, and 4 cubes. The checks are (0 + 2)/2 = 1, (2 + 4)/2 = 3, (0 + 4)/2 = 2, and (2 + 6)/2 = 4. Each board has just one circle, so that check completes it.'),
('Listen for','A child should count two joined shapes even when one stack is empty. If they divide by the number of nonempty stacks, return to pointing at the two places. If they move cubes from the squares, rebuild the reference stacks and use spare copies.'),
('Held hints','First: "Which places have a line to this circle?" Then: "Can the spare cubes make two equal piles?" If needed, let the child deal one cube to each sharing pile in turn.'),
('Optional extension','Compare the two left boards. Increasing the 2-square to 4 increases the circle from 1 to 2. Then try squares 1 and 5; the circle is 3. Use this to invite a prediction, without requiring a written rule.'),
('Enough for now','Accept a physical build and a child checking another child\'s board. No numeral writing is required. Continue with inverse-build Problem 3 or 4 before linked circles if that keeps the mathematical choices in the child\'s hands.')])

page('K-1 Problem 2','Student page 2 | Keep both circles correct together',figs=['K2.1','K2.2','K2.3','K2.4'],sections=[
('Exact answers','The circle pairs, left to right from the top row down, are (1,2), (2,1), (2,4), and (4,2). Completed paths are shown above.'),
('Every check','Row 1: (0 + 2)/2 = 1 and (1 + 3)/2 = 2. Row 2: (3 + 1)/2 = 2 and (2 + 0)/2 = 1. Row 3: (0 + 4)/2 = 2 and (2 + 6)/2 = 4. Row 4: (6 + 2)/2 = 4 and (4 + 0)/2 = 2.'),
('Why these are forced','At any two-neighbor circle, the gap below it equals the gap above it. The three gaps between the endpoints therefore match. Endpoints 0 and 3 give three gaps of 1; endpoints 0 and 6 give three gaps of 2. Reversing the endpoint order reverses the filling. This is an adult completeness argument; children may show it by equal-height steps.'),
('Held hints','First: "Can you check the left circle without changing either circle?" Then check the right. If changing one breaks the other, ask the child to keep trying a whole pair. Later: "What happens when you turn the first board around?"'),
('Optional extension','Try a path with endpoints 3 and 6 and two circles: its values are 4 and 5. Adding three cubes to every stack of the first board preserves all averages. A quick child can explain this by giving three extra cubes to each equal-sharing pile.')])

page('K-1 Problem 3','Student page 3 | Revised inverse construction | Exactly 10 fillings',figs=['K3'],sections=[
('Interpret the positions','Record each filling as (top square, lower-left square, lower-right square). The circle always contains 2. The three square amounts are chosen afresh for a new attempt, then held fixed while checking. Rotating the amounts to different printed positions makes a different filling.'),
('Exact list','(0,3,3), (1,2,3), (1,3,2), (2,1,3), (2,2,2), (2,3,1), (3,0,3), (3,1,2), (3,2,1), (3,3,0). Each square is between 0 and 3 and every triple totals 6, so its three equal shares contain 2 cubes each.'),
('Why none are missing','Three shares of 2 require 6 cubes among the squares. Sort any three square amounts from smallest to largest just for classification. If the smallest is 0, the other two must both be 3. If the smallest is 1, the other two must be 2 and 3. If the smallest is 2, all three must be 2. A smallest amount of 3 totals at least 9. Thus the only shapes of answer are (0,3,3), (1,2,3), and (2,2,2). Their distinct positional arrangements number 3, 6, and 1, totaling 10.'),
('Held hints','First: "How many spare cubes make three equal piles of two?" Later: "Could a square be empty?" If a child is finding repeats, offer to group records by the top-square amount. Do not announce the total of ten before the search.'),
('Recording and extension','Use the ten small diagrams for dots, numerals, or adult scribing; the large diagram is the stack mat. If the circle changes to 1 with the same 0-3 square bound, there are again 10 fillings: permutations of (0,0,3), (0,1,2), and (1,1,1). Compare their counts rather than demanding a formula.')])

page('K-1 Problem 4','Student page 4 | Three different cards | Exactly 8 fillings',figs=['K4'],sections=[
('Exact list','In (left square, circle, right square) order: (0,1,2), (2,1,0), (0,2,4), (4,2,0), (1,2,3), (3,2,1), (2,3,4), (4,3,2). The child uses three distinct cards from 0,1,2,3,4 on each attempt, not all five at once. Left-right reversals count separately.'),
('Check and completeness','The circle is halfway between its square values. It cannot be 0 or 4: with distinct cards, an average cannot equal the smallest or largest available value. Circle 1 requires endpoint sum 2, giving only 0 and 2. Circle 2 requires sum 4, giving 0 and 4 or 1 and 3; the pair 2 and 2 repeats a card. Circle 3 requires sum 6, giving only 2 and 4. Each allowable unordered pair has two left-right orders, so 2 + 4 + 2 = 8.'),
('Held hints','First: "Does your circle have one equal share of the square stacks?" Then: "Have you kept a record before moving a card?" If the search is stuck, ask whether 0 could go in the circle and why. Let the child choose how to organize the collection.'),
('Watch the convention','The squares are freely chosen during construction but become fixed for the averaging check. The middle card does not join itself. A reflected board is not the same positional record, even if it uses the same three cards.'),
('Optional extension','Allow repeated values, using written copies of cards. Then there are 13 ordered triples: the eight above plus the five constant triples (0,0,0) through (4,4,4). For endpoints of the same parity, their average is a card; there are 3 x 3 + 2 x 2 = 13 such ordered endpoint pairs.')])

page('K-1 Problem 5','Student page 5 | Can either board contain a five-cube circle',figs=['K5.1','K5.2'],sections=[
('Answer','Neither board can have a 5-cube circle while every circle works. Their only legal circle pairs are (1,2) and (2,3). The equal-gap argument on page 3 fixes these pairs; their checks are (0+2)/2=1, (1+3)/2=2, (1+3)/2=2, and (2+4)/2=3.'),
('A child-sized impossibility argument','Suppose a working board has a circle of 5 or more. Choose its tallest stack, which is taller than every fixed square. Its joined stacks are no taller. To average to the same tall height, every joined stack would need that height too. Follow the line until it reaches a square; that square would have to be just as tall, contradicting its printed stack. For these paths, the walk to a square takes at most two edges.'),
('Concrete forced-check alternative','On the upper board, putting 5 in the left circle forces 10 in the right to average with 0, but that right circle would then need twice 10 = 5 + 3, which is false. Putting 5 in the right forces 7 in the left, but then twice 7 cannot equal 0 + 5. On the lower board, 5 on the left forces 9 on the right and fails twice 9 = 5 + 4; 5 on the right forces 6 on the left and fails twice 6 = 1 + 5.'),
('Held hints','First let the child try 5 in either circle and check both. Then: "Which stack is tallest now? Could sharing stacks no taller than it make that tallest height?" A demonstration with unequal spare stacks can establish that one shorter neighbor lowers the equal share.'),
('Stop or extend','Accept a spoken argument supported by pointing. A useful extension asks whether a circle can be taller than 4 on the lower board; the same argument rules it out. Finding the actual filling is helpful evidence, but a single filling alone does not rule out every other one.')])

page('K-1 Problem 6','Student page 6 | One fixed square controls a connected board',figs=['K6.1','K6.2'],sections=[
('Exact answers','Both triangle circles contain 2. All three circles on the four-cycle contain 3. In each case every circle sees two equal neighbor values, so its average is that same value.'),
('Why no circle can differ','If any stack were taller than the square, choose a tallest stack. Both its neighbors must match that height, and repeating along the connected board forces the fixed square to match, which it does not. If a stack were shorter, choose a shortest stack and use the same reasoning with "no shorter" in place of "no taller." Thus all stacks must equal their square.'),
('Held hints','First: "Can you build a filling that definitely works?" After an attempted different circle, ask the child to check all circles without moving any cubes. Later: "What would the tallest stack force its neighbors to do? What if we start at the shortest?"'),
('Important distinction','The square is not required to average its neighbors. In these constant fillings it happens to do so, but that coincidence must not become a new rule. The proof stops when a forced value reaches the fixed square.'),
('Optional extension','Replace the square\'s 2 by 4: every triangle circle must become 4. Or redraw the square as a circle and move to Problem 7. Removing the fixed condition creates several possible constants, rather than a different nonconstant shape of solution.')])

page('K-1 Problem 7','Student page 7 | Two boards with no fixed squares',figs=['K7.1','K7.2'],sections=[
('Exact answers','Each board has six fillings. On the triangle the triples are (0,0,0), (1,1,1), (2,2,2), (3,3,3), (4,4,4), (5,5,5). On the four-circle path, repeat the same chosen value four times. The two printed boards are separate questions; the answer is six for each.'),
('Why every listed filling works','At a circle joined to one neighbor, the average is that neighbor\'s value. At a circle joined to two equal neighbors, the average is again their common value. Hence any constant 0 through 5 is legal on either board.'),
('Why none are missing','Triangle: take a tallest stack. Both neighbors must be equally tall to average to it, so all three match. Path: the left endpoint must equal its sole neighbor. That next circle averages the equal endpoint and the third circle, forcing the third to match too; the right endpoint then matches the third. Thus a nonconstant filling cannot work.'),
('Held hints','First: "Does an end circle have one neighbor or two?" For the triangle: "Check the tallest stack using copies of its neighbors." If needed, the adult can scribe each found constant in a recording diagram, leaving the child to decide what has not yet been tried.'),
('Optional extension','Use numbers 0 through 6: each connected board has seven fillings. With no upper bound and whole cubes, it has infinitely many constant fillings. This illustrates why a board with no fixed squares cannot have a bound supplied by square values. Do not invent an average for an isolated circle.')])

page('Grades 2-3 Problem 1','Student page 1 | Change one square to raise the circle by two',figs=['M1.1','M1.2','M1.3','M1.4'],sections=[
('Starting answers','In reading order the circles are 4,4,5,5: (1+7)/2=4, (0+3+9)/3=4, (2+8)/2=5, and (2+5+8)/3=5.'),
('Every possible single-square change','On each two-neighbor board, add 4 to either one square. On each three-neighbor board, add 6 to any one square. These are all possibilities: with d neighbors, raising the average by 2 raises the required neighbor total by 2d; the one changed square must supply that entire increase.'),
('Examples to check','Upper left: change 1 to 5, giving (5+7)/2=6. Upper right: change 0 to 6, giving (6+3+9)/3=6. Lower left: change 2 to 6, giving (6+8)/2=7. Lower right: change 2 to 8, giving (8+5+8)/3=7. The original square amounts are fixed only within a filling; this task explicitly asks for a changed board.'),
('Held hints','First: "How many equal shares do you need on this board?" Then: "If each share grows by two cubes, how many more cubes are needed altogether?" Let a child first predict whether changing the top square or a side square matters.'),
('Optional extension','Add 6 to one neighbor: the circle increases by 3 on a two-neighbor board and by 2 on a three-neighbor board. In general, adding k to one of d neighbors raises the circle by k/d. Keep fractional cases for children ready for that representation.')])

page('Grades 2-3 Problem 2','Student page 2 | Four simultaneous fillings',figs=['M2.1','M2.2','M2.3','M2.4'],sections=[
('Exact answers','The three path pairs are (3,6), (5,8), and (3,3). The bottom tree has left circle 4 and right circle 6.'),
('Every check','First path: (0+6)/2=3 and (3+9)/2=6. Second: (2+8)/2=5 and (5+11)/2=8. Third: both averages are (3+3)/2=3. Tree: the left circle has three neighbors, so (0+6+6)/3=4; the right has two, so (4+8)/2=6.'),
('Why the filling is unique','Equal gaps force each path. For the tree, call the circles u and v from left to right. The conditions are 3u=6+v and 2v=u+8. Doubling the first and substituting the second gives 6u=12+(u+8), so 5u=20, u=4, and v=6. This algebra is adult verification, not a procedure to require of children.'),
('Held hints','First: "Which circles change their check when this number changes?" Later, ask the child to trace the exact neighbors of the tree\'s left circle. Do not average the three fixed squares directly: the left circle is joined to the other circle, not to the square labeled 8.'),
('Optional extension','Add 1 everywhere on the tree, including every square: the new fixed values are 1,7,9 and the circles are 5,7. This is the middle board of Problem 5, so choose whether to reveal that connection now or save it for later.')])

page('Grades 2-3 Problem 3','Student page 3 | No circle above every square',figs=['M3.1','M3.2'],sections=[
('Answer and examples','Neither board permits a hidden peak. The path is 1,3,5,7,9; its circle averages are (1+5)/2=3, (3+7)/2=5, and (5+9)/2=7. The tied diamond has both circles 5, with (2+8+5)/3=5 for each.'),
('Complete impossibility argument','If some circle exceeded every square, choose the largest value M on that board. It must be on a circle. Every neighbor is at most M, and their average is M, so all neighbors equal M. Along a path to a square, every intervening circle forces the same value onward. The square would then equal M even though every square was assumed smaller. This contradiction rules out all possible fillings, not merely the attempts made at the table.'),
('A specific check on the diamond','Each circle is joined directly to squares 2 and 8. A largest circle value greater than 8 would average at least two strictly smaller neighbors together with a neighbor no larger than itself. That average is strictly smaller than the chosen largest value, impossible.'),
('Held hints','First: "Which stack would you check first if one were taller than all squares?" Then: "Could an equal share be as tall as the tallest neighbor if one of the neighbors is shorter?" If children have a local argument only, ask them to follow lines to a square.'),
('Optional extension','Ask for a circle smaller than every square. Choosing a smallest value gives the reversed argument. Keep the conclusion inclusive: the rule proves no value outside the square range, not that every circle must be strictly inside it.')])

page('Grades 2-3 Problem 4','Student page 4 | A circle can equal a square extreme',figs=['M4.1','M4.2'],sections=[
('Exact answers','Upper board circle values from left to right are 3,6,6. Its last two circles equal the largest square, 6; no circle equals its smallest square, 0. Lower board circle values from left to right are 0,0,3. Its first two circles equal the smallest square, 0; no circle equals its largest square, 6.'),
('Every check','Upper: (0+6)/2=3; (6+6)/2=6; the right endpoint averages its sole neighbor 6. Lower: the left endpoint averages its sole neighbor 0; (0+0)/2=0; (0+6)/2=3.'),
('Why the constant tail is forced','In the upper board, the endpoint circle equals its only neighbor. The neighboring circle then averages the square 6 and a value equal to itself, forcing both circles to be 6. The lower board has the same argument at its left end, with square 0. Each remaining circle sits directly between the two squares, so its average is 3.'),
('What the example teaches','All places are connected, yet the fixed square in the middle stops the chain of averaging constraints. A square may be joined to unequal values without changing. Thus a circle can equal a global extreme even when another square has a different value elsewhere in the same connected component.'),
('Held hints','First: "Check the circle with just one neighbor." Then: "Does the square in the middle have to pass an averaging test?" Use these only after children have tried filling the board.'),
('Optional extension','Replace the upper middle square by a circle while keeping square 0 fixed. The whole board must then be 0, by the one-fixed-value argument. Ask children which condition changed before discussing the new result.')])

page('Grades 2-3 Problem 5','Student page 5 | Is there a second filling',figs=['M5.1','M5.2','M5.3'],sections=[
('Exact answers','Top path: (6,9). Middle tree: left circle 5, right circle 7. Bottom diamond: top and bottom circles both 7. None has a different filling with the same square values.'),
('Checks','Path: (3+9)/2=6 and (6+12)/2=9. Tree: (1+7+7)/3=5 and (5+9)/2=7. Diamond: each circle has exactly the two square neighbors, so (4+10)/2=7.'),
('A complete board-by-board uniqueness argument','For the path, the three equal gaps between 3 and 12 must each be 3. For the diamond, each circle is directly forced to 7 independently of the other; there is no vertical edge between them. For the tree let u,v be the left and right circles. We have 3u=8+v and 2v=u+9. Hence 6u=16+2v=25+u, giving u=5 and v=7. Every filling must satisfy these relations, so there is no second one.'),
('Held hints','First: "Keep the squares, change a circle, and check every circle again." Later: "Which circles have only fixed neighbors?" For a child ready for a general reason, ask how two proposed fillings differ at each place, then use page 3. Signed differences are optional; the concrete arguments above suffice for the printed boards.'),
('Watch for','Trying many pairs does not by itself establish uniqueness over unrestricted numbers. The packet does not impose an integer-only search here. A forced argument, or the general maximum-principle proof, rules out fractional alternatives too.'),
('Optional extension','Increase every square by 2; increasing every circle by 2 gives a legal filling. Uniqueness then says this shifted filling is the only one. Ask the child why the average shifts by exactly 2.')])

page('Grades 2-3 Problem 6','Student page 6 | Complete collections with no squares',figs=['M6.1','M6.2'],sections=[
('Exact answers','Each board has six fillings. For the upper four-cycle, every circle equals a common c in {0,1,2,3,4,5}. For the lower three-circle path, the same six constants are possible. There are six per board, rather than six shared choices for both boards together.'),
('Existence and completeness','Each constant works because every neighbor has that value. For the cycle, choose a largest circle value M. Its two neighbors must both equal M; continuing around the cycle forces the fourth circle to equal M. For the path, each endpoint must equal the middle circle because it has only one neighbor; then the middle average also works. No nonconstant filling survives.'),
('Held hints','First: "What condition does an end circle have?" On the cycle: "Suppose you choose the largest number on your board. Can either neighbor be smaller?" If a child lists constants without an explanation, ask what would happen to a board containing two different heights.'),
('Compare with earlier work','The earlier uniqueness result used fixed square values and access to at least one square from every place. These boards have no squares. The hypotheses changed, so six solutions do not contradict that result.'),
('Optional extension','If these two separate boards were treated as one disconnected board, the cycle could choose c and the path could choose d independently. There would be 6 x 6 = 36 fillings. Joining them by an edge would force a common constant, returning to six. This prepares Grades 4-5 Problem 6.')])

page('Grades 4-5 Problem 1','Student page 1 | Find fillings and investigate uniqueness',figs=['O1.1','O1.2','O1.3'],sections=[
('Exact answers','The top path has circle values (5,10), the middle tree has (5,7), and the tied diamond has (8,8). None has a second filling with the same fixed values.'),
('Every check','Path: (0+10)/2=5 and (5+15)/2=10. Tree: (0+8+7)/3=5 and (5+9)/2=7. Tied diamond: (2+14+8)/3=8 at each circle.'),
('Complete reasons for uniqueness','The path has three equal gaps totaling 15, forcing gaps of 5. For the tree, 3u=8+v and 2v=u+9 imply 6u=16+(u+9), so u=5 and v=7. For the tied diamond, 3u=16+v and 3v=16+u. Subtracting gives 4(u-v)=0, hence u=v. Then 3u=16+u gives u=v=8. The general proof is held until Problem 5, but is available on page 3.'),
('Held hints','First: "Can you verify both circles on one frozen board?" Later: "Which of these boards looks unchanged if its two circles exchange places?" Symmetry suggests equal values, but symmetry alone is not a proof of uniqueness; the equations or maximum principle supply that proof.'),
('Optional extension','Offer a second-looking assignment with a small error, such as path (4,8). The left circle works, but the right does not: (4+15)/2 is not 8. Ask children to explain why checking only one circle is insufficient.')])

page('Grades 4-5 Problem 2','Student page 2 | Rule out thirteen or more',figs=['O2.1','O2.2'],sections=[
('Answer','Neither board can contain a circle value of 13 or more. The upper board is bounded above by its largest square, 11; the lower by its largest square, 10. In fact their displayed legal solutions have circle values (3,6,7,8) and (6,6).'),
('Exact checks of the upper board','Name the top-row circles u=3 and v=6 from left to right, and the lower circles w=7 and z=8 from left to right. Then u=(0+6)/2=3; v=(3+6+7+8)/4=6; w=(6+8)/2=7; z=(7+6+11)/3=8. Notice the four neighbors at v, including the diagonal to z.'),
('Exact checks of the lower board','Each diamond circle is 6 and has neighbors 2,10,6, so (2+10+6)/3=6.'),
('Complete impossibility argument','Suppose a circle is at least 13 and choose the greatest value M on that finite board. It is a circle, since all squares are smaller. Every neighbor must equal M for the circle to average to M. Following a path to a square propagates M through circles to the first square, a contradiction. This proves more than the requested threshold: no value can exceed 11 on the upper board or 10 on the lower.'),
('Held hints','First: "Which places are joined to the top-right circle?" Then: "If a circle of 13 forces a larger neighbor, which value should your argument start with?" A largest value avoids an endless search for ever larger neighbors.'),
('Optional extension','Ask whether 11 can occur in a circle of the upper board. It cannot: a circle at the maximum forces equality through the circle subgraph to the square 0 or 6, contradicting their values. Keep this stronger claim separate from the general non-strict bound.')])

page('Grades 4-5 Problem 3','Student page 3 | The finite maximum and minimum principle',figs=['O3'],sections=[
('The claim','Every circle value lies between the smallest and largest square values it can reach. Reachability means belonging to the same connected component. The board is finite, and every component contains a square. These assumptions are part of the theorem.'),
('Complete upper-bound proof','Fix one component, and let B be its largest square value. Suppose some value exceeds B. Since the component is finite, it has a greatest value M, with M>B. A place carrying M is a circle. All its neighbors have values at most M. If any were smaller, their average would be smaller than M; hence every neighbor equals M. Choose a path from that circle to a square and stop at the first square. Each intermediate circle also has value M and forces the next place to equal M. The final square equals M>B, contradicting the definition of B.'),
('Complete lower-bound proof','Let b be the smallest square value in the component. If any value were smaller than b, take a least value m. It is at a circle. All its neighbors are at least m, so averaging to m forces all to equal m. The same finite path to the first square forces a square value m<b, a contradiction. Apply both arguments separately to each component.'),
('Check of the illustrative graph','The horizontal circles are 4,6,8 and the top circle is 6. Checks: (0+6+6)/3=4, (4+8+6)/3=6, (6+12+6)/3=8, and (4+8)/2=6. This checks an example; it cannot establish the universal theorem by itself.'),
('Held hints and proof repair','Ask, in order only as needed: "Where does the greatest value occur?" "What does its average force?" "How can you get to a square?" If a child says every circle is below every neighbor, offer two equal neighbors. If they walk through a square, stop them there: no averaging rule applies at it.'),
('Optional extension','Remove finiteness: on an infinite path with square 0 at position 0 and circles at positive integer positions, assigning value n at position n averages correctly but exceeds the only square. There is no greatest circle value. Use this only after the finite proof is secure.')])

page('Grades 4-5 Problem 4','Student page 4 | Equality and the location of fixed squares',figs=['O4.1','O4.2'],sections=[
('Exact answers','Both boards have circle values 4,8,8 in left-to-right order, with the lower board\'s last circle below the branch. On the upper board, the two right circles equal the largest square, 8. On the lower board, no circle equals the largest square, 12.'),
('Every check and why the answers are forced','Upper: the endpoint equals its neighbor; that neighbor then satisfies 2v=8+v, so both tail circles are 8. The other circle is (0+8)/2=4. Lower: the bottom endpoint w equals the branch v. Thus 3v=u+12+w becomes 2v=u+12. Also 2u=v. Hence 4u=u+12, giving u=4 and v=w=8. The branch check is (4+12+8)/3=8.'),
('Explain the difference','On the upper board a fixed square of 8 sits between the constant tail and the circle affected by square 0. Equality propagates from circle to circle until it reaches that square, where it stops. The square need not average 4 and 8. On the lower board that junction is a circle, so it must average the other neighbors, including the lower endpoint. A value 12 would force equality along circles back to square 0, which is impossible.'),
('Held hints','First: "Which place has just one neighbor?" Later: "What changes when a branching place is a circle instead of a square?" If the child invokes connectedness to claim all values must be equal, ask whether their propagation step remains valid at a square.'),
('Optional sharper statement','Look at one connected group of circles after removing the squares. A circle can equal the component\'s largest fixed value M only if every square touching that circle group also has value M: equality spreads throughout that circle group and into each touching square. Conversely, if all those touching squares are M, the maximum and minimum bounds force every circle in the group to be M. This precisely explains the upper tail.')])

page('Grades 4-5 Problem 5','Student page 5 | A general uniqueness argument',figs=['O5'],sections=[
('Answer and exact example','There cannot be two different fillings under the stated finite-board and square-reachability assumptions. Both printed copies have left circle 6, upper circle 10, and lower circle 8. Checks: (0+10+8)/3=6, (6+8+16)/3=10, and (6+10+8)/3=8.'),
('Complete proof','Assume two legal fillings f and g with identical square values. At each place write the signed difference h=f-g. Every square now has value 0. If a circle has d neighbors, d f(circle) is the sum of their f-values, and d g(circle) is the sum of their g-values. Subtract: d h(circle) is the sum of their h-values. Thus the difference board obeys exactly the same averaging rule.'),
('', 'The maximum principle applied to this difference board says h<=0 everywhere, since every fixed square is 0. The minimum principle says h>=0 everywhere. Both together force h=0 at every place, so the two original fillings coincide. This includes fractional or negative candidate values; it is not merely a bounded integer search.'),
('Held hints','First: "How could you record exactly where two proposed fillings differ?" Then: "What are the differences at the squares?" If the signed arithmetic is unfamiliar, use one simple path pair to practice subtracting at each place before returning to the proof. Save the full difference-board suggestion until needed.'),
('Do not overclaim existence','Uniqueness means at most one filling. The displayed assignments prove existence for these examples by passing every check. The proof above alone does not construct a filling for an arbitrary board or guarantee a whole-number filling. Problem 7 makes that distinction concrete.'),
('Optional extension','If one fixed-value board has solution f and another on the same graph has solution g, their pointwise average has boundary values equal to the average of the two boundary assignments and obeys the averaging rule. Verify by distributing sums; then uniqueness identifies it as the only filling for those averaged boundaries.')])

page('Grades 4-5 Problem 6','Student page 6 | Five fillings and twenty-five fillings',figs=['O6.1','O6.2'],sections=[
('Upper board','There are five fillings: (0,0,0), (1,1,1), (2,2,2), (3,3,3), (4,4,4). A largest triangle value forces both other values to equal it, and each constant works.'),
('Lower board','The dashed outline groups both disconnected pairs as one board; it is not an edge. Every filling is (a,a,b,b), read left to right, with a and b independently chosen from {0,1,2,3,4}. Each pair has a single edge, so each endpoint must equal its only neighbor. No line relates the two pairs. Thus there are 5 x 5 = 25 fillings.'),
('Complete list in compact form','For a=0: (0,0,b,b) for b=0,1,2,3,4. For a=1: (1,1,b,b) for those five b. Repeat for a=2, a=3, and a=4. These five disjoint rows each contain five distinct fillings, and every legal filling belongs to exactly one row because its left pair determines a and its right pair determines b.'),
('Held hints','First: "Is that dashed outline a line joining two circles?" If the child has only five lower fillings, ask whether the right pair must match the left. If the child has 625 unrestricted four-tuples, ask them to test the single-neighbor rule on each pair.'),
('Generalization with proof','For c connected components made only of circles, each component is constant by the largest-value argument. With q allowed values, each component has q independent choices, so there are q^c fillings. This requires positive-degree circles; isolated vertices need a separate definition and are not part of the task.'),
('Optional extension','Add an edge between the two pairs. Now all four circles are connected, forcing a=b and leaving five fillings. With numbers unrestricted over the reals, each original pair may take any real constant, so there are infinitely many fillings rather than 25.')])

page('Grades 4-5 Problem 7','Student page 7 | Whole-number existence and fraction cards',figs=['O7.1','O7.2','O7.3','O7.4'],sections=[
('Exact answers','Row 1 needs 1/2, so no whole-number filling. Row 2 has circle values 1 and 2, so a whole-number filling exists. Row 3 has circle value 1, also a whole-number filling. Row 4 needs 1/3 and 2/3, so no whole-number filling.'),
('Every check','Row 1: (0+1)/2=1/2. Row 2: (0+2)/2=1 and (1+3)/2=2. Row 3: (0+2)/2=1. Row 4: (0+2/3)/2=1/3 and (1/3+1)/2=2/3. The printed area cards represent the needed halves and thirds; a drawing or number can be placed in the circle without cutting cards.'),
('Why the failures are genuine','For a one-circle path the average of the endpoints is forced, so Row 1 cannot have an integer alternative. For Row 4, equal gaps divide the endpoint change of 1 over three edges, forcing each gap to be 1/3. Its two circle values are therefore 1/3 and 2/3. The fractional fillings demonstrate existence over rational numbers; the exact forced values demonstrate nonexistence over whole numbers.'),
('Held hints','First: "What does half of one whole look like?" Then: "If the three gaps are equal and together make one whole, what is one gap?" Avoid treating a decimal approximation as an exact check.'),
('Optional extension','For integer endpoints A and B on a path of L equal edges, every value is an integer exactly when B-A is divisible by L. Necessity: the first gap equals (B-A)/L and is the difference of integers. Sufficiency: if that gap is an integer, all successive A+i(B-A)/L are integers and satisfy the averaging rule. This path criterion does not automatically describe general graphs.')])

page('Sources and fidelity limits','Separate adult-guide step | Checked 3 October 2026',sections=[
('Primary mathematical source','Peter G. Doyle and J. Laurie Snell, <i>Random Walks and Electric Networks</i>, version dated 5 July 2006, sections 1.1.5 and 1.2.2, especially PDF pages 11 and 17 (also printed pages 11 and 17). These passages give maximum and uniqueness principles in one- and two-dimensional settings. Source: <link href="https://math.dartmouth.edu/~doyle/docs/walkspdf/walks.pdf" color="#174e70">math.dartmouth.edu/~doyle/docs/walkspdf/walks.pdf</link>. Relevant passages were rechecked for this guide. The finite arbitrary-graph path formulation and all packet-specific computations are independently supplied here.'),
('Math-circle teaching reference','Natasha Rozhkovskaya, <i>Math Circles for Elementary School Students</i>, "Introduction: Berkeley 2009" (repository EPUB, OEBPS/part0010.xhtml). The introduction describes a grades 1-3 program with adult assistance available to each child and parents actively helping with problems and handouts. That supports the adult-at-table arrangement. It does not establish this guide\'s timing, hint sequence, averaging launch, or age fit; those are untested planning choices.'),
('Packet and project sources','This guide follows Week 20 final/k-1.pdf (7 pages; GA20-K-v3), final/grades-2-3.pdf (6 pages; GA20-23-v2), and final/grades-4-5.pdf (7 pages; GA20-45-v3), together with their final/src/build_packets.py source. Context: the project AGENTS.md and README.md; Week 20 PROMPT.md; review.md, review-math.md, and REVISE.md. The final student pages, rather than unrevised review answers, determine the tasks here.'),
('Revision fidelity','K-1 Problem 3 is the revised bounded inverse construction, with 10 positional fillings. It replaces the two earlier star examples. K-1 sharing counts empty neighboring places. The lower board in Grades 4-5 Problem 6 is visibly grouped as one disconnected board and has 25 fillings. Recording copies added in the final K-1 pages retain positional distinctions.'),
('What has been verified','The editable checker solves the fixed-value boards with exact rational Gaussian elimination, checks all circle equations, enumerates the bounded all-ways tasks, and tests every single-square change in Grades 2-3 Problem 1. Mathematical arguments in this guide establish completeness beyond the finite checks. Every guide page was rendered and inspected. October 4 added worked visual examples; all numbered tasks and their solutions remain unchanged. The changed pages were rendered and inspected.'),
('Limits and the next use record','This is not a classroom report, a claim that all problems fit one hour, a numerical-convergence theorem, or a continuum PDE lesson. After use, record the date, pages actually attempted, what children built or explained, where an adult had to restate a rule, and whether recording or cube handling slowed the work. Separate observed behavior from guesses about its cause. Keep unused questions available for a later session.')])

# Concise front matter; the original detailed pages remain in order.
import json
from pathlib import Path
_OV=json.loads((Path(__file__).parent/'mathematical-overview.json').read_text())
PAGES.insert(0,dict(title=_OV['title'],sub='Adult theorem map | Draft and unpiloted',figs=[],sections=_OV['sections'],table=None))
