from pathlib import Path
import sys,json
ROOT=Path(__file__).resolve().parents[2]
ROWS={
11:[('Sink removed: stops, loops and capacity','K–1 / 2–3, adult reads and records','Expands optional base-guide closed-triangle seed with contrasting stopping and capacity cases; seed is not counted separately.'),('The largest one-chip avalanche','2–3 / 4–5','Firing cascades from all stable states, rather than base repeated addition-state orbits.'),('All legal histories from known starts','4–5','Reuses base middle P3 starts; the new investigation enumerates all legal words and missing orders. Inverse reconstruction stays with adults.')],
12:[('Unlike-color noncrossing pairs','K–1 / 2–3','Label compatibility changes existence/count, rather than ordinary pairing enumeration.'),('Paths under a ceiling','2–3 / 4–5','A height restriction and ground-return classification, beyond base code conversion.'),('Local path surgery and shortest raising routes','4–5','A move-distance/lower-bound question on familiar paths.')],
13:[('Sharing roads versus sharing junctions','K–1 / 2–3','Internal vertex capacity changes the route model; base reserves edges only.'),('Two assigned deliveries','2–3 / 4–5','Specified endpoint pairs expose an obstruction the single-source theorem does not settle.'),('Several lanes on a road','4–5','Integer capacities and one-lane comparison, with a matching capacity-cut proof.')],
14:[('Ears and peeling','K–1 / 2–3','Structure of triangle adjacency and ear removal, beyond base counts/flips.'),('Three labels and a corner cover','2–3 / 4–5','Color propagation gives a new all-triangle cover certificate.'),('Turn-symmetric triangulations','4–5','Rotation constraints and complete fixed-set classification, rather than identifying rotated fillings.')],
15:[('Farthest-site ownership','K–1 / 2–3, oral/string entry','Reverses comparison, producing an empty center cell.'),('Grid-step distances and large ties','2–3 / 4–5','Changes the distance rule; tie regions and nonconvexity differ from base straight-line cells.'),('The clearest place','4–5','Optimizes nearest-site clearance in a bounded frame rather than only drawing inserted-site regions.')],
16:[('A fourth interior label','K–1 oral star / 2–3 mesh / 4–5 minimum proof','Changes the interior-label assumption while preserving the boundary; zero RBY remains compatible with a minimum of three any-three cells. Base center refinement is not counted.'),('A square and its boundary word','2–3 / 4–5','General boundary parity on a changed domain; same boundary can give different counts.'),('Positive and negative rainbows','4–5','Oriented signed count strengthens ordinary rainbow parity.')],
17:[('Has RR occurred?','K–1 / 2–3, partner operation','Persistent occurrence memory differs from base last-card/suffix machine.'),('Two even counts','2–3 / 4–5','Combines red and blue parity memory with a four-state minimality witness.'),('Can a machine remember balance?','4–5','Concrete continuation collision proves no fixed finite state count handles arbitrary balanced rows.')]
}
text='# Weeks 11–17 return-visit inventory\n\nSeven familiar themes; **21 investigations**, three per theme. These may support multiple visits; no number of classroom visits or completed child investigations is claimed. All companions are separate draft/unpiloted review material. Base student PDFs, base guides, Week1 encore, AGENTS.md and global indexes are untouched by this range.\n\n'
text+='Layout: one shared student collection per week, with a prerequisite/band header on each page; separate five-page theorem-first adult guide. Youngest-child routes are offered only where the concrete mathematics supports them. Suitable bands describe entry/readiness rather than age restrictions. All exact material fit, stock, procedures and classroom response remain untested.\n\n'
text+='| Week | Investigation | Suitable entry | New versus base | Companion | Status |\n|---|---|---|---|---|---|\n'
for n,rows in ROWS.items():
 tag=f'week-{n:02}-return-visit';pdf=ROOT/f'lowell-math-circle-year-2/week-{n:02}/{tag}.pdf'
 audit=ROOT/f'plans/encore-11-17/week-{n:02}-page-audit.json'
 checked=pdf.exists() and audit.exists() and all('passed' in x.get('visual_review','').lower() for x in json.loads(audit.read_text())) and (ROOT/f'plans/encore-11-17/week-{n:02}-rebuild-audit.json').exists()
 status='delivered; every final page inspected and extracted rebuild checked' if checked else ('delivered; final QA pending' if pdf.exists() else 'kernel independently checked; workflow/release pending')
 for title,bands,new in rows:
  paths=f'[student](../lowell-math-circle-year-2/week-{n:02}/{tag}.pdf), [adult](../lowell-math-circle-year-2/week-{n:02}/{tag}-facilitator.pdf)'
  text+=f'| {n} | {title} | {bands} | {new} | {paths} | {status} |\n'
text+='\nEditable source directories: `lowell-math-circle-year-2/source/week-NN-return-visit/`; portable ZIPs beside them: `lowell-math-circle-year-2/source/week-NN-return-visit-source.zip`. [Kernel outlines, source notes and independent checks](encore-11-17/) hold this range’s planning data. Workflow runs: `tmp/worksheet-runs/encore-week-NN-20261004-v1/`, each using a fresh writer, critic, math reviewer and reviser. Adult guides were written separately. Guide matching to all actual final student problems is complete.\n\n'
text+='Independent kernel checks cover the proposed mathematics; each release also checks all actual final represented examples: closed chip cycles/capacity, all 24 avalanche trials and legal orders, inverse/history words; colored pairings and all four-pair Dyck paths, ceiling counts and legal swaps; route/vertex packs, assigned-pair paths, integer route multiplicities and cuts; noncrossing hexagon diagonal sets, ears, colorings, covers and rotational symmetries; exact grid distance examples and continuum clearance proofs with sampled support; all 256 four-label fillings (27 without RBY), their any-three minimum and recoloring witnesses, all 81 square boundaries/two diagonals, and 192 signed Sperner fillings; base local refinements are checked only as an optional signed-count connection; deterministic machine constructions and exact continuation witnesses. General results have explicit assumptions and elementary arguments in the guides.\n\n'
text+='All seven packages are delivered: 14 PDFs, 27 student pages and 35 adult pages (62 total), plus seven portable source ZIPs. The shared closing-quotation correction is recorded in `encore-11-17/quote-fix-review.md` and `quote-fix-audit.json`; student PDFs and all guide pages outside page2 retain their previous content. Coverage and page-level QA details are recorded per week in `encore-11-17/week-NN-release-review.md` and rebuild equality JSON. Rendering and digital checks are not physical readiness or classroom piloting. No commit, push, remote upload or publication is performed.\n'
(ROOT/'plans/bonus-weeks-11-17.md').write_text(text)
